### ISSUE TITLE
Alpha: java.lang.AssertionError: Assert failed: (cljs-util/is-file-instance? cache-root)

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#100]
I'm using:

```js
"shadow-cljs": "^2.0.0-alpha19",
```

and:

```
$ shadow-cljs watch browser
shadow-cljs - config: /Users/chen/repo/mvc-works/coworkflow/shadow-cljs.edn version: 2.0.0-alpha8
shadow-cljs - updating dependencies
Retrieving thheller/shadow-cljs/2.0.0-alpha8/shadow-cljs-2.0.0-alpha8.pom from http://clojars.org/repo/
Retrieving org/clojure/clojurescript/1.9.908/clojurescript-1.9.908.pom from http://repo1.maven.org/maven2/
Retrieving org/clojure/google-closure-library/0.0-20170809-b9c14c6b/google-closure-library-0.0-20170809-b9c14c6b.pom from http://repo1.maven.org/maven2/
Retrieving org/clojure/google-closure-library-third-party/0.0-20170809-b9c14c6b/google-closure-library-third-party-0.0-20170809-b9c14c6b.pom from http://repo1.maven.org/maven2/
```

and the error part:

```
[:browser] Configuring build.
Sep 29, 2017 3:20:52 PM clojure.tools.logging$eval334$fn__337 invoke
WARNING: failed to handle server msg {:type :start-autobuild}
java.lang.AssertionError: Assert failed: (cljs-util/is-file-instance? cache-root)
	at shadow.cljs.devtools.config$make_cache_dir.invokeStatic(config.clj:112)
	at shadow.cljs.devtools.config$make_cache_dir.invoke(config.clj:112)
	at shadow.cljs.devtools.server.worker.impl$build_configure.invokeStatic(impl.clj:116)
	at shadow.cljs.devtools.server.worker.impl$build_configure.invoke(impl.clj:90)
	at shadow.cljs.devtools.server.worker.impl$fn__21954.invokeStatic(impl.clj:207)
	at shadow.cljs.devtools.server.worker.impl$fn__21954.invoke(impl.clj:199)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at shadow.cljs.devtools.server.util$server_thread$fn__21838$fn__21839$fn__21843.invoke(util.clj:159)
	at shadow.cljs.devtools.server.util$server_thread$fn__21838$fn__21839.invoke(util.clj:158)
	at shadow.cljs.devtools.server.util$server_thread$fn__21838.invoke(util.clj:143)
	at clojure.core.async$thread_call$fn__7981.invoke(async.clj:442)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[:worker-error {:type :start-autobuild} #error {
 :cause "Assert failed: (cljs-util/is-file-instance? cache-root)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: (cljs-util/is-file-instance? cache-root)"
   :at [shadow.cljs.devtools.config$make_cache_dir invokeStatic "config.clj" 112]}]
 :trace
 [[shadow.cljs.devtools.config$make_cache_dir invokeStatic "config.clj" 112]
  [shadow.cljs.devtools.config$make_cache_dir invoke "config.clj" 112]
  [shadow.cljs.devtools.server.worker.impl$build_configure invokeStatic "impl.clj" 116]
  [shadow.cljs.devtools.server.worker.impl$build_configure invoke "impl.clj" 90]
  [shadow.cljs.devtools.server.worker.impl$fn__21954 invokeStatic "impl.clj" 207]
  [shadow.cljs.devtools.server.worker.impl$fn__21954 invoke "impl.clj" 199]
  [clojure.lang.MultiFn invoke "MultiFn.java" 233]
  [shadow.cljs.devtools.server.util$server_thread$fn__21838$fn__21839$fn__21843 invoke "util.clj" 159]
  [shadow.cljs.devtools.server.util$server_thread$fn__21838$fn__21839 invoke "util.clj" 158]
  [shadow.cljs.devtools.server.util$server_thread$fn__21838 invoke "util.clj" 143]
  [clojure.core.async$thread_call$fn__7981 invoke "async.clj" 442]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1149]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 624]
  [java.lang.Thread run "Thread.java" 748]]}]
```

The project I was trying to migrate: https://github.com/mvc-works/coworkflow/tree/5277caddf89ffd7ff39dded83d6fa56574761c2a

**Comment by thheller** [comment]
You say you are using `2.0.0-alpha19` but the start command says `version: 2.0.0-alpha8`?

Maybe you upgraded the global but not the one in your project?

I clone the project and it did compile fine?

```
[zilence@zpro ~/code/tmp/coworkflow]$ yarn upgrade shadow-cljs@next
yarn upgrade v1.1.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ shadow-cljs@2.0.0-alpha19
✨  Done in 7.91s.

[zilence@zpro ~/code/tmp/coworkflow]$ shadow-cljs watch browser
shadow-cljs - config: /Users/zilence/code/tmp/coworkflow/shadow-cljs.edn version: 2.0.0-alpha19
shadow-cljs - updating dependencies
Retrieving thheller/shadow-cljs/2.0.0-alpha19/shadow-cljs-2.0.0-alpha19.pom from http://clojars.org/repo/
Retrieving mvc-works/shell-page/0.1.2/shell-page-0.1.2.pom from http://clojars.org/repo/
Retrieving respo/respo/0.5.2/respo-0.5.2.pom from http://clojars.org/repo/
Retrieving mvc-works/verbosely/0.1.0-rc/verbosely-0.1.0-rc.pom from http://clojars.org/repo/
Retrieving respo/respo/0.6.2/respo-0.6.2.pom from http://clojars.org/repo/
Retrieving mvc-works/shell-page/0.1.2/shell-page-0.1.2.jar from http://clojars.org/repo/
Retrieving respo/respo/0.6.2/respo-0.6.2.jar from http://clojars.org/repo/
Retrieving thheller/shadow-cljs/2.0.0-alpha19/shadow-cljs-2.0.0-alpha19.jar from http://clojars.org/repo/
Retrieving mvc-works/verbosely/0.1.0-rc/verbosely-0.1.0-rc.jar from http://clojars.org/repo/
shadow-cljs - dependencies updated
shadow-cljs - re-building aot cache on startup, that will take some time.
shadow-cljs - starting ...
shadow-cljs - server running at http://localhost:8081
shadow-cljs - socket repl running at localhost:58339
shadow-cljs - nrepl running at localhost/127.0.0.1:58341
shadow-cljs - watching build :browser
[:browser] Configuring build.
[:browser] Compiling ...
[:browser] Build completed. (159 files, 57 compiled, 0 warnings, 11.06s)
```

**Comment by jiyinyiyong** [comment]
It's strange. I added:

```js
"shadow-cljs": "^2.0.0-alpha19",
```

and checked with `yarn list`, but found:

```
├─ shadow-cljs@2.0.0-alpha9
```

Trying to specify a specific version...

**Comment by thheller** [comment]
I think that `shadow-cljs` 2.0 is approaching a state where it is as stable as it was before 2.0.

I will probably drop the `@next` tag soon which should make version management less of an issue.

But there it is again, you say `2.0.0-alpha19` and the list says `2.0.0-alpha9` (9 not 19).

Not sure whats going on.

**Comment by jiyinyiyong** [comment]
I think it's okay now.

So there **WAS** a bug in `alpha8` or `alpha9` right?

**Comment by thheller** [comment]
Yes, there was a problem in those versions.

**Comment by thheller** [comment]
Hmm I'm having the exact same issue at the moment.

My `package.json` is
```
{
  "devDependencies": {
    "shadow-cljs": "^2.0.0-alpha19"
  },
  "dependencies": {
    "react": "^15.0.0",
    "react-dom": "^15.0.0"
  }
}
```

Yet when I run `yarn` it install `2.0.0-alpha9`. I guess it doesn't like the `alpha19` version tag and treats it as a string rather than a number. So `alpha9` sorts higher than `alpha19`.

I'm dropping the `alpha` tag now.
