### ISSUE TITLE
java.lang.ArithmeticException: integer overflow

### ISSUE THREAD

**Issue by anderskitson** [thheller/shadow-cljs#1002]
I am not sure what is causing this error.

I am running 

` "shadow-cljs": "2.17.8"`

and am trying to get cider to work and connect to nRepl in emacs

Now at first I was on a older version of shadow-cljs but cider complained that the nRepl version was too old, so I upgraded shadow-cljs, but now when I run `npm run dev` I get the following error, but when I connect in cider it says the nRepl version has been updated to the required one it asked for before

```
java.lang.ArithmeticException: integer overflow
	at clojure.lang.Numbers.throwIntOverflow(Numbers.java:1576)
	at clojure.lang.Numbers.multiply(Numbers.java:1960)
	at nrepl.bencode$read_long.invokeStatic(bencode.clj:128)
	at nrepl.bencode$read_long.invokePrim(bencode.clj)
	at nrepl.bencode$read_netstring_STAR_.invokeStatic(bencode.clj:155)
	at nrepl.bencode$read_netstring_STAR_.invoke(bencode.clj:153)
	at nrepl.bencode$read_token.invokeStatic(bencode.clj:246)
	at nrepl.bencode$read_token.invoke(bencode.clj:236)
	at nrepl.bencode$read_bencode.invokeStatic(bencode.clj:256)
	at nrepl.bencode$read_bencode.invoke(bencode.clj:253)
	at nrepl.transport$bencode$fn__6986$fn__6987.invoke(transport.clj:122)
	at nrepl.transport$bencode$fn__6986.invoke(transport.clj:122)
	at nrepl.transport$fn_transport$fn__6940.invoke(transport.clj:50)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

this is my shadow-cljs.edn file, I have tried with and without cider-nrepl, with the same error above

```
{:source-paths ["src"]

 :dependencies [
                ;;[proto-repl "0.3.1"]
                [binaryage/devtools "0.9.10"]
                [reagent "1.1.0"]
                [re-frame "0.10.6"]
                [day8.re-frame/re-frame-10x "1.2.1"]
                [bidi "2.1.5"]
                [cider/cider-nrepl "0.28.3"]
                [kibu/pushy "0.3.8"]
                [com.andrewmcveigh/cljs-time "0.5.2"]]

 :nrepl        {:port 3333}

 :builds {:app {:target :browser
                :output-dir "public/js"
                :asset-path "/js"

                :modules {:main {:init-fn app.core/init}}

                :compiler-options {:closure-defines {re-frame.trace/trace-enabled? true
                                                     day8.re-frame.tracing/trace-enabled? true}}

                :devtools {:http-root   "public"
                           :http-port   3000
                           :preloads    [day8.re-frame-10x.preload]}}}}

```

Any help would be greatly appreciated.

Thanks

**Comment by thheller** [comment]
What does `npm run dev` do?

I don't know much about emacs/cider so I'm not much help debugging related issues. Never seen that error before but shadow-cljs is also nowhere on the stacktrace. Might be something with your nrepl setup. I believe it does read a config file from `~/.nrepl/` and `.nrepl.edn` or so locally?

**Comment by anderskitson** [comment]
npm run dev runs 

`shadow-cljs watch app`

there is a folder called `.shadow-cljs` which has a nrepl.port file which is just 3333 

but I don't see a .nrepl or .nrepl.edn

I only asked here because I thought the implementation if nRepl was built into shadow, but not exactly sure how this all works.

**Comment by anderskitson** [comment]
This is the project I cloned from with the upgrade I did to shadow being the main change, I can ask in there as well, but don't know what kind of answer I will get.

https://github.com/jacekschae/learn-re-frame-course-files

**Comment by thheller** [comment]
shadow-cljs does bring in the nrepl dependency itself. Version 0.9.0, which also appears to be the version cider-nrepl uses so there should be no problem. I assume you get this error when you connect with emacs? `shadow-cljs watch app` itself runs fine I assume?

I really don't know what emacs does on connect so I can't say much.

**Comment by anderskitson** [comment]
the strange thing is I get this error, even before I connect in emacs. Do you know the best place to ask a question for this? nRepl github probably?

**Comment by thheller** [comment]
when exactly do you get this error? I mean just running `shadow-cljs watch app` alone? A full log would help to provide context.

**Comment by anderskitson** [comment]
So this is the fullstack after running `watch app`

```
➜  cheffy git:(master) ✗ npm run dev

> Cheffy@0.0.1 dev
> shadow-cljs watch app

shadow-cljs - config: /Users/anderskitson/clojure-script/learn-re-frame-course-2.0/cheffy/shadow-cljs.edn  cli version: 2.7.25  node: v12.21.0
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - HTTP server for :app available at http://localhost:3000
shadow-cljs - server version: 2.7.25 running at http://localhost:9630
shadow-cljs - nREPL server started on port 3333
shadow-cljs - watching build :app
[:app] Configuring build.
ERROR:
java.lang.ArithmeticException: integer overflow
	at clojure.lang.Numbers.throwIntOverflow(Numbers.java:1526)
	at clojure.lang.Numbers.multiply(Numbers.java:1892)
	at nrepl.bencode$read_long.invokeStatic(bencode.clj:128)
	at nrepl.bencode$read_long.invokePrim(bencode.clj)
	at nrepl.bencode$read_netstring_STAR_.invokeStatic(bencode.clj:155)
	at nrepl.bencode$read_netstring_STAR_.invoke(bencode.clj:153)
	at nrepl.bencode$read_token.invokeStatic(bencode.clj:246)
	at nrepl.bencode$read_token.invoke(bencode.clj:236)
	at nrepl.bencode$read_bencode.invokeStatic(bencode.clj:256)
	at nrepl.bencode$read_bencode.invoke(bencode.clj:253)
	at nrepl.transport$bencode$fn__855$fn__856.invoke(transport.clj:122)
	at nrepl.transport$bencode$fn__855.invoke(transport.clj:122)
	at nrepl.transport$fn_transport$fn__809.invoke(transport.clj:50)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[:app] Compiling ...
```

**Comment by thheller** [comment]
```
shadow-cljs - server version: 2.7.25 running at http://localhost:9630
```

You are not running `"shadow-cljs": "2.17.8"`?

**Comment by anderskitson** [comment]
hmm, must have done install in wrong terminal window anyways I did that and now get 

`shadow-cljs - server version: 2.17.8 running at http://localhost:9630`

But alas still the same java error

**Comment by anderskitson** [comment]
I also noticed this really not sure what is going on

```
--- node_modules/highlight_DOT_js/lib/languages/python.js:11
Cannot convert ECMASCRIPT_2018 feature "RegExp unicode property escape" to targeted output language.
```

**Comment by thheller** [comment]
Sorry, I don't have any guess about what may be happening. Dunno how it ends up running nrepl code on its own? Is it something you are maybe including in your code? Maybe a `user.clj`? Can you share the full code repo?

The `Cannot convert ECMASCRIPT_2018 feature ...` error you can ignore. That is unrelated.

**Comment by anderskitson** [comment]
Here is the repo from my current state, I also messaged the course creator and linked him here, so maybe there is more insight he can provide

https://github.com/anderskitson/cheffy_test

**Comment by thheller** [comment]
Hmm yeah sorry I don't know about that nrepl error. It works just fine for me.

The repo does contain a `.lsp` and `.clj-kondo` dir. So maybe there is some other stuff running that I don't have that is interfering with this somehow.

The actual build failure caused by `Cannot convert ECMASCRIPT_2018 feature ` you can fix by setting `:dev {:compiler-options {:output-feature-set :es-next}}` in the build config. It compiles fine after that for me.

**Comment by anderskitson** [comment]
Are you saying you cloned my repo and it was working for you?

**Comment by thheller** [comment]
As in I don't get the `java.lang.ArithmeticException: integer overflow` error at all yes. The other build failure I get and fixed as above.

**Comment by anderskitson** [comment]
ok interesting, thanks for looking into this. Must be something with my machine, or configuration somewhere. I will look into it further. Thanks

**Comment by jacekschae** [comment]
@anderskitson, which Java version are you running? 

I would recommend to delete `node_modules` and try `npm install` again.

I cloned your repo and run `npm run dev` and end up with the same error:

```bash
...
[:app] Build failure:
Closure compilation failed with 1 errors
--- node_modules/highlight_DOT_js/lib/languages/python.js:11
Cannot convert ECMASCRIPT_2018 feature "RegExp unicode property escape" to targeted output language.
```

Then as Thomas mentioned added in the build config `:compiler-options`

```clojure
{:source-paths ["src"]

 :dependencies [;;[proto-repl "0.3.1"]
                [binaryage/devtools "0.9.10"]
                [reagent "1.1.0"]
                [re-frame "0.10.6"]
                [day8.re-frame/re-frame-10x "1.2.1"]
                [bidi "2.1.5"]
                ;;[nrepl "0.9.0"]
                ;;[cider/cider-nrepl "0.28.3"]
                [kibu/pushy "0.3.8"]
                [com.andrewmcveigh/cljs-time "0.5.2"]]

 :nrepl        {:port 3333}

 :builds {:app {:dev {:compiler-options {:output-feature-set :es-next}} ; <- compiler options
                :target :browser
                :output-dir "public/js"
                :asset-path "/js"

                :modules {:main {:init-fn app.core/init}}

                :compiler-options {:closure-defines {re-frame.trace/trace-enabled? true
                                                     day8.re-frame.tracing/trace-enabled? true}}

                :devtools {:http-root   "public"
                           :http-port   3000
                           :preloads    [day8.re-frame-10x.preload]}}}}
```

and end up with a working build:

```
cheffy ⊷ master $ npm run dev

> Cheffy@0.0.1 dev
> shadow-cljs watch app

shadow-cljs - config: /Users/jacek/Projects/temp/cheffy_test/cheffy/shadow-cljs.edn
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
shadow-cljs - HTTP server available at http://localhost:3000
shadow-cljs - server version: 2.17.8 running at http://localhost:9630
shadow-cljs - nREPL server started on port 3333
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (594 files, 593 compiled, 0 warnings, 18.26s)
[:app] Compiling ...
[:app] Build completed. (594 files, 0 compiled, 0 warnings, 0.12s)
``` 

Hope this helps.

**Comment by jacekschae** [comment]
Setting compiler options in the shadow-cljs config `-> :builds :app :complier-options` works as well.

```clojure
{:source-paths ["src"]

 :dependencies [;;[proto-repl "0.3.1"]
                [binaryage/devtools "0.9.10"]
                [reagent "1.1.0"]
                [re-frame "0.10.6"]
                [day8.re-frame/re-frame-10x "1.2.1"]
                [bidi "2.1.5"]
                ;;[nrepl "0.9.0"]
                ;;[cider/cider-nrepl "0.28.3"]
                [kibu/pushy "0.3.8"]
                [com.andrewmcveigh/cljs-time "0.5.2"]]

 :nrepl        {:port 3333}

 :builds {:app {:target :browser
                :output-dir "public/js"
                :asset-path "/js"

                :modules {:main {:init-fn app.core/init}}

                :compiler-options {
                    :output-feature-set :es-next ; <- compiler options
                    :closure-defines {re-frame.trace/trace-enabled? true
                                                     day8.re-frame.tracing/trace-enabled? true}}

                :devtools {:http-root   "public"
                           :http-port   3000
                           :preloads    [day8.re-frame-10x.preload]}}}}
```

@thheller by setting `:dev :compiler-options` this only affects `dev` env and by setting it in the build config it also affects release?

**Comment by thheller** [comment]
Only setting this for dev because this is caused by the re-frame-10x dependencies which won't be included in a release build. You can set it for the entire build but likely that isn't needed.

**Comment by Macroz** [comment]
In case someone runs into this kind of error message. I got it when *browsing* to the nREPL port instead of the correct app port. CIDER etc. were not related.

```
java.lang.ArithmeticException: integer overflow
	at clojure.lang.Numbers.throwIntOverflow(Numbers.java:1576)
	at clojure.lang.Numbers.multiply(Numbers.java:1960)
	at nrepl.bencode$read_long.invokeStatic(bencode.clj:128)
	at nrepl.bencode$read_long.invokePrim(bencode.clj)
	at nrepl.bencode$read_netstring_STAR_.invokeStatic(bencode.clj:155)
	at nrepl.bencode$read_netstring_STAR_.invoke(bencode.clj:153)
	at nrepl.bencode$read_token.invokeStatic(bencode.clj:246)
	at nrepl.bencode$read_token.invoke(bencode.clj:236)
	at nrepl.bencode$read_bencode.invokeStatic(bencode.clj:256)
	at nrepl.bencode$read_bencode.invoke(bencode.clj:253)
	at nrepl.transport$bencode$fn__6161$fn__6162.invoke(transport.clj:122)
	at nrepl.transport$bencode$fn__6161.invoke(transport.clj:122)
	at nrepl.transport$fn_transport$fn__6115.invoke(transport.clj:50)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
