### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:50584

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#126]
```
=>> yarn watch
yarn run v1.2.1
$ shadow-cljs watch browser
shadow-cljs - config: /Users/chen/repo/cirru/coir-viewer/shadow-cljs.edn version: 2.0.54
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:50584
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```
=>> sudo lsof -i tcp:50584
=>> netstat -vanp tcp | grep 50584
```

feeling strange.

If the `target/` folder is useful http://repo.tiye.me/gist/bad-target.zip

**Comment by thheller** [comment]
Seems like the server process was killed without being shutdown properly.

You can delete the `target/shadow-cljs/*.port` files manually for now. I'll add a check to delete them whenever a connect fails.
