### ISSUE TITLE
"$CLJS is not defined" during reload in :nodejs mode

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#132]
```clojure
(defn main! [] (println "Test loade!") (run-tests))
```

with test configs:

```edn
          :test {:target :node-script
                 :output-to "target/test.js"
                 :main recollect.test/main!
                 :devtools {:after-load recollect.test/main!}}
```

in:

```
├─ shadow-cljs@2.0.72
```

got error with code https://github.com/Cumulo/recollect/tree/debugging-test 

```
ReferenceError: $CLJS is not defined
    at /Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:116:68
    at shadow.cljs.devtools.client.node.build_complete.vec__9474 (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:103:30)
    at Object.shadow$cljs$devtools$client$node$build_complete [as build_complete] (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:108:12)
    at Object.shadow$cljs$devtools$client$node$process_message [as process_message] (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:140:6)
    at WebSocket.<anonymous> (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:173:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/Users/chen/repo/cumulo/recollect/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/Users/chen/repo/cumulo/recollect/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/chen/repo/cumulo/recollect/node_modules/ws/lib/Receiver.js:330:12)
```

As it mentioned the file is:

```
/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:116:68
```

I managed to find a file called:

```
/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow.cljs.devtools.client.node.js
```

with a `$CLJS` in line 371:

```js
var temp__5457__auto__ = ((cljs.core.seq(shadow.cljs.devtools.client.env.after_load))?goog.getObjectByName(shadow.cljs.devtools.client.env.after_load,$CLJS):null);
```

which is the only `$CLJS` in the specific file.

Full error:

```
DEVTOOLS: app start recollect.test.main_BANG_
failed to process message {:type :build-complete, :build-config {:target :node-script, :output-to "target/test.js", :main recollect.test/main!, :devtools {:after-load recollect.test/main!}, :id :test, :build-id :test}, :info {:timings {:compile-prepare {:enter 1510411932453, :exit 1510411932453}, :compile-finish {:enter 1510411932635, :exit 1510411932635}, :flush {:enter 1510411932635, :exit 1510411932648}}, :modules [{:goog-base true, :entries [cljs.user shadow.cljs.devtools.client.node recollect.test], :sources [[:shadow.build.classpath/resource "goog/base.js"] [:shadow.build.classpath/resource "goog/debug/error.js"] [:shadow.build.classpath/resource "goog/dom/nodetype.js"] [:shadow.build.classpath/resource "goog/string/string.js"] [:shadow.build.classpath/resource "goog/asserts/asserts.js"] [:shadow.build.classpath/resource "goog/reflect/reflect.js"] [:shadow.build.classpath/resource "goog/math/long.js"] [:shadow.build.classpath/resource "goog/math/integer.js"] [:shadow.build.classpath/resource "goog/object/object.js"] [:shadow.build.classpath/resource "goog/array/array.js"] [:shadow.build.classpath/resource "goog/structs/structs.js"] [:shadow.build.classpath/resource "goog/functions/functions.js"] [:shadow.build.classpath/resource "goog/math/math.js"] [:shadow.build.classpath/resource "goog/iter/iter.js"] [:shadow.build.classpath/resource "goog/structs/map.js"] [:shadow.build.classpath/resource "goog/uri/utils.js"] [:shadow.build.classpath/resource "goog/uri/uri.js"] [:shadow.build.classpath/resource "goog/string/stringbuffer.js"] [:shadow.build.classpath/resource "cljs/core.cljs"] [:shadow.build.classpath/resource "clojure/walk.cljs"] [:shadow.build.classpath/resource "cljs/spec/gen/alpha.cljs"] [:shadow.build.classpath/resource "clojure/string.cljs"] [:shadow.build.classpath/resource "cljs/spec/alpha.cljs"] [:shadow.build.classpath/resource "cljs/repl.cljs"] [:shadow.cljs.repl/resource "cljs/user.cljs"] [:shadow.build.classpath/resource "cljs/tools/reader/impl/utils.cljs"] [:shadow.build.classpath/resource "cljs/tools/reader/reader_types.cljs"] [:shadow.build.classpath/resource "cljs/tools/reader/impl/inspect.cljs"] [:shadow.build.classpath/resource "cljs/tools/reader/impl/errors.cljs"] [:shadow.build.classpath/resource "cljs/tools/reader/impl/commons.cljs"] [:shadow.build.classpath/resource "cljs/tools/reader.cljs"] [:shadow.build.classpath/resource "shadow/cljs/devtools/client/env.cljs"] [:shadow.build.js-support/require "ws"] [:shadow.build.classpath/resource "cljs/tools/reader/edn.cljs"] [:shadow.build.classpath/resource "cljs/reader.cljs"] [:shadow.build.classpath/resource "shadow/cljs/devtools/client/node.cljs"] [:shadow.build.classpath/resource "cljs/pprint.cljs"] [:shadow.build.classpath/resource "cljs/test.cljs"] [:shadow.build.classpath/resource "recollect/util.cljs"] [:shadow.build.classpath/resource "recollect/types.cljs"] [:shadow.build.classpath/resource "clojure/set.cljs"] [:shadow.build.classpath/resource "recollect/schema.cljs"] [:shadow.build.classpath/resource "recollect/diff.cljs"] [:shadow.build.classpath/resource "recollect/test.cljs"] [:shadow.build.modules/append :main]], :prepend "#!/usr/bin/env node\n(function(){\n", :module-name "main.js", :output-name "main.js", :append "\n})();\n", :module-id :main, :append-js "\n\ncljs.core.apply.cljs$core$IFn$_invoke$arity$2(recollect.test.main_BANG_, process.argv.slice(2));", :depends-on #{}}], :sources [{:resource-id [:shadow.build.classpath/resource "goog/base.js"], :resource-name "goog/base.js", :output-name "goog.base.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/debug/error.js"], :resource-name "goog/debug/error.js", :output-name "goog.debug.error.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/dom/nodetype.js"], :resource-name "goog/dom/nodetype.js", :output-name "goog.dom.nodetype.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/string/string.js"], :resource-name "goog/string/string.js", :output-name "goog.string.string.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/asserts/asserts.js"], :resource-name "goog/asserts/asserts.js", :output-name "goog.asserts.asserts.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/reflect/reflect.js"], :resource-name "goog/reflect/reflect.js", :output-name "goog.reflect.reflect.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/math/long.js"], :resource-name "goog/math/long.js", :output-name "goog.math.long.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/math/integer.js"], :resource-name "goog/math/integer.js", :output-name "goog.math.integer.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/object/object.js"], :resource-name "goog/object/object.js", :output-name "goog.object.object.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/array/array.js"], :resource-name "goog/array/array.js", :output-name "goog.array.array.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/structs/structs.js"], :resource-name "goog/structs/structs.js", :output-name "goog.structs.structs.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/functions/functions.js"], :resource-name "goog/functions/functions.js", :output-name "goog.functions.functions.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/math/math.js"], :resource-name "goog/math/math.js", :output-name "goog.math.math.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/iter/iter.js"], :resource-name "goog/iter/iter.js", :output-name "goog.iter.iter.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/structs/map.js"], :resource-name "goog/structs/map.js", :output-name "goog.structs.map.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/uri/utils.js"], :resource-name "goog/uri/utils.js", :output-name "goog.uri.utils.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/uri/uri.js"], :resource-name "goog/uri/uri.js", :output-name "goog.uri.uri.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "goog/string/stringbuffer.js"], :resource-name "goog/string/stringbuffer.js", :output-name "goog.string.stringbuffer.js", :type :goog, :ns nil, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/core.cljs"], :resource-name "cljs/core.cljs", :output-name "cljs.core.js", :type :cljs, :ns cljs.core, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "clojure/walk.cljs"], :resource-name "clojure/walk.cljs", :output-name "clojure.walk.js", :type :cljs, :ns clojure.walk, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/spec/gen/alpha.cljs"], :resource-name "cljs/spec/gen/alpha.cljs", :output-name "cljs.spec.gen.alpha.js", :type :cljs, :ns cljs.spec.gen.alpha, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "clojure/string.cljs"], :resource-name "clojure/string.cljs", :output-name "clojure.string.js", :type :cljs, :ns clojure.string, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/spec/alpha.cljs"], :resource-name "cljs/spec/alpha.cljs", :output-name "cljs.spec.alpha.js", :type :cljs, :ns cljs.spec.alpha, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/repl.cljs"], :resource-name "cljs/repl.cljs", :output-name "cljs.repl.js", :type :cljs, :ns cljs.repl, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.cljs.repl/resource "cljs/user.cljs"], :resource-name "cljs/user.cljs", :output-name "cljs.user.js", :type :cljs, :ns cljs.user, :module :main, :warnings [], :from-jar nil} {:resource-id [:shadow.build.classpath/resource "cljs/tools/reader/impl/utils.cljs"], :resource-name "cljs/tools/reader/impl/utils.cljs", :output-name "cljs.tools.reader.impl.utils.js", :type :cljs, :ns cljs.tools.reader.impl.utils, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/tools/reader/reader_types.cljs"], :resource-name "cljs/tools/reader/reader_types.cljs", :output-name "cljs.tools.reader.reader_types.js", :type :cljs, :ns cljs.tools.reader.reader-types, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/tools/reader/impl/inspect.cljs"], :resource-name "cljs/tools/reader/impl/inspect.cljs", :output-name "cljs.tools.reader.impl.inspect.js", :type :cljs, :ns cljs.tools.reader.impl.inspect, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/tools/reader/impl/errors.cljs"], :resource-name "cljs/tools/reader/impl/errors.cljs", :output-name "cljs.tools.reader.impl.errors.js", :type :cljs, :ns cljs.tools.reader.impl.errors, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/tools/reader/impl/commons.cljs"], :resource-name "cljs/tools/reader/impl/commons.cljs", :output-name "cljs.tools.reader.impl.commons.js", :type :cljs, :ns cljs.tools.reader.impl.commons, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/tools/reader.cljs"], :resource-name "cljs/tools/reader.cljs", :output-name "cljs.tools.reader.js", :type :cljs, :ns cljs.tools.reader, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "shadow/cljs/devtools/client/env.cljs"], :resource-name "shadow/cljs/devtools/client/env.cljs", :output-name "shadow.cljs.devtools.client.env.js", :type :cljs, :ns shadow.cljs.devtools.client.env, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.js-support/require "ws"], :resource-name "shadow.js.shim.module$ws.js", :output-name "shadow.js.shim.module$ws.js", :type :goog, :ns shadow.js.shim.module$ws, :module :main, :warnings [], :from-jar nil} {:resource-id [:shadow.build.classpath/resource "cljs/tools/reader/edn.cljs"], :resource-name "cljs/tools/reader/edn.cljs", :output-name "cljs.tools.reader.edn.js", :type :cljs, :ns cljs.tools.reader.edn, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/reader.cljs"], :resource-name "cljs/reader.cljs", :output-name "cljs.reader.js", :type :cljs, :ns cljs.reader, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "shadow/cljs/devtools/client/node.cljs"], :resource-name "shadow/cljs/devtools/client/node.cljs", :output-name "shadow.cljs.devtools.client.node.js", :type :cljs, :ns shadow.cljs.devtools.client.node, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/pprint.cljs"], :resource-name "cljs/pprint.cljs", :output-name "cljs.pprint.js", :type :cljs, :ns cljs.pprint, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "cljs/test.cljs"], :resource-name "cljs/test.cljs", :output-name "cljs.test.js", :type :cljs, :ns cljs.test, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "recollect/util.cljs"], :resource-name "recollect/util.cljs", :output-name "recollect.util.js", :type :cljs, :ns recollect.util, :module :main, :warnings [], :from-jar nil} {:resource-id [:shadow.build.classpath/resource "recollect/types.cljs"], :resource-name "recollect/types.cljs", :output-name "recollect.types.js", :type :cljs, :ns recollect.types, :module :main, :warnings [], :from-jar nil} {:resource-id [:shadow.build.classpath/resource "clojure/set.cljs"], :resource-name "clojure/set.cljs", :output-name "clojure.set.js", :type :cljs, :ns clojure.set, :module :main, :warnings [], :from-jar true} {:resource-id [:shadow.build.classpath/resource "recollect/schema.cljs"], :resource-name "recollect/schema.cljs", :output-name "recollect.schema.js", :type :cljs, :ns recollect.schema, :module :main, :warnings [], :from-jar nil} {:resource-id [:shadow.build.classpath/resource "recollect/diff.cljs"], :resource-name "recollect/diff.cljs", :output-name "recollect.diff.js", :type :cljs, :ns recollect.diff, :module :main, :warnings [], :from-jar nil} {:resource-id [:shadow.build.classpath/resource "recollect/test.cljs"], :resource-name "recollect/test.cljs", :output-name "recollect.test.js", :type :cljs, :ns recollect.test, :module :main, :warnings [], :from-jar nil} {:resource-id [:shadow.build.modules/append :main], :resource-name "shadow/module/main/append.js", :output-name "shadow.module.main.append.js", :type :goog, :ns shadow.module.main.append, :module :main, :warnings [], :from-jar nil}], :compiled #{[:shadow.build.classpath/resource "recollect/test.cljs"]}}} ReferenceError: $CLJS is not defined
    at /Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:116:68
    at shadow.cljs.devtools.client.node.build_complete.vec__9474 (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:103:30)
    at Object.shadow$cljs$devtools$client$node$build_complete [as build_complete] (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:108:12)
    at Object.shadow$cljs$devtools$client$node$process_message [as process_message] (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:140:6)
    at WebSocket.<anonymous> (/Users/chen/repo/cumulo/recollect/target/shadow-cljs/builds/test/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:173:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/Users/chen/repo/cumulo/recollect/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/Users/chen/repo/cumulo/recollect/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/chen/repo/cumulo/recollect/node_modules/ws/lib/Receiver.js:330:12)
```

**Comment by thheller** [comment]
Fixed in `shadow-cljs@2.0.73`.
