### ISSUE TITLE
Error not handled: doseq requires an even number of forms in binding vector

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#142]
Full log https://gist.github.com/chenyong/636fe8c72a7365f541d7e47060e355ae

**Comment by jiyinyiyong** [comment]
Another error occurs when I use `assert` and it fails. I don't get the code related to the assertion, but a `Pipe broken` error:

```
JS runtime disconnected.
JS runtime connected.
[2017-11-29 23:05:26 - SEVERE] error in manifold.utils/future-with
java.io.IOException: Pipe broken
	at java.io.PipedInputStream.read(PipedInputStream.java:321)
	at java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at byte_streams$fn__12515.invokeStatic(byte_streams.clj:701)
	at byte_streams$fn__12515.invoke(byte_streams.clj:676)
	at byte_streams.protocols$fn__11456$G__11451__11465.invoke(protocols.clj:9)
	at byte_streams$fn__12335$f__12138__auto____12337$fn__12339.invoke(byte_streams.clj:452)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5587.invoke(core.clj:2738)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$empty_QMARK_.invokeStatic(core.clj:6126)
	at clojure.core$empty_QMARK_.invoke(core.clj:6126)
	at manifold.stream.seq.SeqSource.take(seq.clj:41)
	at manifold.stream.graph$sync_connect$f__644__auto____2124.invoke(graph.clj:255)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$3.run(Executor.java:318)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__536$f__537.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java
```

**Comment by thheller** [comment]
I'll probably remove ALL stacktraces from normal output and just print them to the logfile.

No idea about that manifold error though. I doubt very much it has anything to do with `assert`.

**Comment by jiyinyiyong** [comment]
You are right about the `Pipe broken` error. I can't reproduce it by failing the assertion. 😕

**Comment by thheller** [comment]
`shadow.*` or `cljs.*` aren't even on the stack so its probably related to the websocket server with a dropped connection or so.

**Comment by thheller** [comment]
Unfortunately the CLJS compiler throws this exception during analysis as a generic `ex-info` with no additional data. This makes it rather hard to distinguish errors and I don't want to hardcode certain error messages.

I have however shortened the printed stack so it doesn't dump 200 lines of useless info.
