### ISSUE TITLE
"REPL client error Error: server sent no subprotocol even though requested" in debugging Node.js

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#155]
In a [project](https://github.com/Cirru/bisection-key) forked from [minimal-shadow-cljs-nodejs](https://github.com/minimal-xyz/minimal-shadow-cljs-nodejs), I got the error immediately after running `node target/main.js`:

```text
REPL client error Error: server sent no subprotocol even though requested
    at ClientRequest._req.on (/Users/chen/repo/cirru/bisection-key/node_modules/ws/lib/WebSocket.js:691:28)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketOnData (_http_client.js:471:11)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:608:20)
REPL client disconnected
```

and compiler throw errors too:

```text
[:app] Compiling ...
[:app] Build completed. (40 files, 20 compiled, 0 warnings, 18.17s)
JS runtime connected.
Exception in thread "async-dispatch-5" java.lang.Error: java.io.IOException: UT002002: Channel is closed
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: UT002002: Channel is closed
	at io.undertow.websockets.core.WebSocketChannel.send(WebSocketChannel.java:333)
	at io.undertow.websockets.core.WebSockets.sendBlockingInternal(WebSockets.java:992)
	at io.undertow.websockets.core.WebSockets.sendBlockingInternal(WebSockets.java:986)
	at io.undertow.websockets.core.WebSockets.sendTextBlocking(WebSockets.java:200)
	at shadow.undertow$websocket$reify__21109$fn__21159$state_machine__5461__auto____21178$fn__21180.invoke(undertow.clj:73)
	at shadow.undertow$websocket$reify__21109$fn__21159$state_machine__5461__auto____21178.invoke(undertow.clj:73)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at shadow.undertow$websocket$reify__21109$fn__21159.invoke(undertow.clj:73)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	... 2 more
```

Tried and it happens in `2.0.124`, `2.0.123`, `2.0.122`, `2.0.121`, works fine in `2.0.120`.

Found related issue on Google https://github.com/esl/MongooseIM/issues/1221 however I don't understand what's happening...

**Comment by thheller** [comment]
Fixed in `shadow-cljs@2.0.125`.
