### ISSUE TITLE
NoSuchFileException: shadow-cljs.log.0.lck

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#163]
Started seeing this issue periodically.  File doesn't exist but not sure why it expects it to be, it doesn't appear to be causing issues and goes away for awhile if you nuke the target directory and rerun.
```
shadow-cljs - config: /Users/kharriger/projects/synchrony-forensics/shadow-cljs.edn version: 2.0.128
shadow-cljs - updating dependencies
Retrieving binaryage/devtools/maven-metadata.xml from https://clojars.org/repo/
Retrieving cider/cider-nrepl/0.16.0-SNAPSHOT/maven-metadata.xml from https://clojars.org/repo/
shadow-cljs - dependencies updated
shadow-cljs - starting ...
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: /Users/kharriger/projects/2018/synchrony-forensics/target/shadow-cljs/shadow-cljs.log.0.lck
java.nio.file.NoSuchFileException: /Users/kharriger/projects/2018/synchrony-forensics/target/shadow-cljs/shadow-cljs.log.0.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:263)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1777)
	at java.util.logging.Logger.log(Logger.java:735)
	at org.jboss.logging.JDKLogger.doLogf(JDKLogger.java:64)
	at org.jboss.logging.Logger.logf(Logger.java:2398)
	at org.xnio._private.Messages_$logger.greeting(Messages_$logger.java:115)
	at org.xnio.Xnio.<clinit>(Xnio.java:99)
	at io.undertow.Undertow.start(Undertow.java:114)
	at shadow.undertow$start.invokeStatic(undertow.clj:147)
	at shadow.undertow$start.invoke(undertow.clj:115)
	at shadow.cljs.devtools.server$start_http$fn__21394.invoke(server.clj:115)
	at shadow.cljs.devtools.server$start_http.invokeStatic(server.clj:114)
	at shadow.cljs.devtools.server$start_http.invoke(server.clj:110)
	at shadow.cljs.devtools.server$start_system.invokeStatic(server.clj:143)
	at shadow.cljs.devtools.server$start_system.invoke(server.clj:124)
	at shadow.cljs.devtools.server$start_BANG_.invokeStatic(server.clj:221)
	at shadow.cljs.devtools.server$start_BANG_.invoke(server.clj:211)
	at shadow.cljs.devtools.server$start_BANG_.invokeStatic(server.clj:214)
	at shadow.cljs.devtools.server$start_BANG_.invoke(server.clj:211)
	at shadow.cljs.devtools.server$from_cli.invokeStatic(server.clj:330)
	at shadow.cljs.devtools.server$from_cli.invoke(server.clj:306)
	at shadow.cljs.devtools.cli$blocking_action.invokeStatic(cli.clj:124)
	at shadow.cljs.devtools.cli$blocking_action.invoke(cli.clj:111)
	at shadow.cljs.devtools.cli$main.invokeStatic(cli.clj:172)
	at shadow.cljs.devtools.cli$main.doInvoke(cli.clj:127)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$apply.invoke(core.clj:652)
	at shadow.cljs.devtools.cli$_main.invokeStatic(cli.clj:214)
	at shadow.cljs.devtools.cli$_main.doInvoke(cli.clj:212)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
shadow-cljs - HTTP server for ":browser" available at http://localhost:8700
shadow-cljs - server running at http://0.0.0.0:9630
shadow-cljs - nrepl running at /0.0.0.0:8777
shadow-cljs - watching build :browser
[:browser] Configuring build.
[:browser] Compiling ...
[:browser] Build completed. (1705 files, 1564 compiled, 0 warnings, 73.21s)
```

**Comment by jiyinyiyong** [comment]
should be better marked as markdown code block.

**Comment by thheller** [comment]
Only explanation I have for this currently is that the `target/shadow-cljs` directory somehow does not exist when the JVM is started. The `shadow-cljs` script however creates this directory always since it writes the generated classpath to `target/shadow-cljs/classpath.edn`.

Is there any chance the `target/shadow-cljs` maybe gets deleted by some other means?

Can you try setting `:cache-root ".shadow-cljs"` in `shadow-cljs.edn` to move it out of the `target` dir which tools like `lein` frequently delete?

**Comment by jiyinyiyong** [comment]
I got this error too after upgrading one of my project from `2.0.133` to `2.0.138`, while I changed my project name.

```
java.nio.file.NoSuchFileException:
/Users/chen/repo/cirru/cumulo-editor/server/target/shadow-cljs/logging.properties.0.lck
```

The folder `cumulo-editor` turned into `calcit-editor`. I think it's just because I changed the name...

**Comment by thheller** [comment]
Ah that is one explanation. The logging config is written into the `target/shadow-cljs` directory. It was using an absolute path which becomes invalid if you move the project.

Just released `shadow-cljs@2.0.139` which now uses a relative path instead. Please delete the `target/shadow-cljs/logging.properties` or the entire `target/shadow-cljs` directory.

**Comment by jiyinyiyong** [comment]
I just removed whole `target/`. 😆

**Comment by kurtharriger** [comment]
I haven't seen it since I nuked the target folder. I’m almost certain I moved my project folder just before I reported this so sounds like this is fixed.
