### ISSUE TITLE
Exception in thread "async-dispatch-7" java.lang.ClassCastException: 

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#175]
Worked fine in `2.0.131`, got this error in `2.0.132`, for both `:target :nodejs` and `:target :browser` when I started watch server and run node/browser code:

```
Exception in thread "async-dispatch-7" java.lang.ClassCastException: shadow.cljs.devtools.server.worker.impl$repl_eval_connect$fn__17929$G__17818__17930 cannot be cast to clojure.lang.Var$Frame
	at clojure.lang.Var.resetThreadBindingFrame(Var.java:103)
	at shadow.cljs.devtools.server.worker.impl$repl_eval_connect$fn__17929$state_machine__5461__auto____17948$fn__17950.invoke(impl.clj:488)
	at shadow.cljs.devtools.server.worker.impl$repl_eval_connect$fn__17929$state_machine__5461__auto____17948.invoke(impl.clj:488)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at shadow.cljs.devtools.server.worker.impl$repl_eval_connect$fn__17929.invoke(impl.clj:488)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

In `2.0.131` I got some errors too, but it still worked:

```
Exception in thread "async-dispatch-3" java.lang.Error: java.io.IOException: UT002002: Channel is closed
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: UT002002: Channel is closed
	at io.undertow.websockets.core.WebSocketChannel.send(WebSocketChannel.java:333)
	at io.undertow.websockets.core.WebSockets.sendBlockingInternal(WebSockets.java:992)
	at io.undertow.websockets.core.WebSockets.sendBlockingInternal(WebSockets.java:986)
	at io.undertow.websockets.core.WebSockets.sendTextBlocking(WebSockets.java:200)
	at shadow.undertow$websocket$reify__21112$fn__21162$state_machine__5461__auto____21181$fn__21183.invoke(undertow.clj:73)
	at shadow.undertow$websocket$reify__21112$fn__21162$state_machine__5461__auto____21181.invoke(undertow.clj:73)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5479.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__454$fn__455.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	... 2 more
```

**Comment by thheller** [comment]
Can't really think of anything that would cause the `java.lang.ClassCastException`.

`UT002002: Channel is closed` this is just sending to a closed websocket, not really a critical error.

**Comment by jiyinyiyong** [comment]
Logs is different now in `2.0.133`:

```
[:browser] Build completed. (182 files, 80 compiled, 0 warnings, 23.38s)
[2018-01-18 00:11:16 - WARNING] stale websocket client, please reload client :browser
[2018-01-18 00:11:16 - WARNING] stale websocket client, please reload client :browser
[2018-01-18 00:11:48 - WARNING] stale websocket client, please reload client :browser
[2018-01-18 00:11:48 - WARNING] stale websocket client, please reload client :browser
```

Files changes does not trigger `:after-load` function.

**Comment by jiyinyiyong** [comment]
fixed by.... removing `target/` and `node_modules/` then reinstalling...

**Comment by chenyong** [comment]
I guess I used the generated `index.html` which refers to old `.js` files since I changed the path.

Not able to reproduce the problem. Closing.

**Comment by chenyong** [comment]
I think "stale websocket client" might confuse people when see this warning. A more friendly warning should tell the user to check if the JavaScript running in browser is identical to the one just compiled. I run into this case for twice, reloading tabs does not help.
