### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#181]
```
shadow-cljs - config: /Users/chen/repo/respo/ui/shadow-cljs.edn version: 2.0.135
shadow-cljs - aot compile
Exception in thread "main" java.lang.UnsupportedClassVersionError: shadow/build/closure/ErrorCollector has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0, compiling:(classpath.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
	at clojure.lang.Compiler.compile1(Compiler.java:7609)
	at clojure.lang.Compiler.compile1(Compiler.java:7599)
	at clojure.lang.Compiler.compile(Compiler.java:7676)
```

```
Caused by: java.lang.UnsupportedClassVersionError: shadow/build/closure/ErrorCollector has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

I guess my Java version is to low, will try upgrade:

```
=>> java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

----

updates: upgrading Java does not help...

**Comment by thheller** [comment]
I switched to Java9 yesterday and didn't realize that this would bump the javac version as well.

`shadow-cljs@2.0.136` should work with Java8+ again.

**Comment by thheller** [comment]
hmm still not fixed. Looking into it.

**Comment by thheller** [comment]
`shadow-cljs@2.0.137` tested with `java version "1.8.0_144"` and working again.

**Comment by jiyinyiyong** [comment]
You upgrade, I upgrade :D

**Comment by thheller** [comment]
Can't recommend upgrading to Java9. Produces some annoying warnings and still requires some extra JVM flags to it starts at all. Safer to stay with Java8.

**Comment by jiyinyiyong** [comment]
okay. tried Java9 again last night. Back to Java8 already.
