### ISSUE TITLE
:require broken in shadow-cljs 2.0.150 but ok in version 2.0.120

### ISSUE THREAD

**Issue by jinwei233** [thheller/shadow-cljs#192]
**the problem**

-  `npm i shadow-cljs@2.0.150 --save` 
- `npm i md5 --save`
- `md5` is required, but is undefined in `foo.cljs`

**code**

`shadow-cljs.edn`:

```clojure
{:source-paths
 ["src"]

 :dependencies
 [[cider/cider-nrepl "0.16.0-SNAPSHOT"]]

 :nrepl
 {:port 8202}

 :builds
 {:script
  {:id        :script
   :target    :node-script
   :main      demo.foo/main
   :output-to "out/script.js"
   :compiler-options {:optimizations :none}
   :devtools {:before-load demo.foo/stop!
              :after-load demo.foo/start!}}}}
```

`foo.cljs`:

```clojure
(ns demo.foo
  (:require ["path" :as path]
            ["fs" :as fs]
            ["md5" :as md5]))

(defn start! []
  "start")

(defn stop! []
  "stop")

(defn ^:export main [name]
  (str "hi" name))

(js/console.log fs)
;; => undefined
(js/console.log md5)
;; => undefined
```

**change shadow-cljs to version 2.0.120 everything goes ok**

**Comment by jiyinyiyong** [comment]
What was the error message? Can you bisect the versions and target the specific version that breaks your code?

**Comment by thheller** [comment]
Works fine on my machine? What was the error message?

https://github.com/thheller/shadow-cljs-issue-192

**Comment by jinwei233** [comment]
@jiyinyiyong error message when I call `main`

```clojure
(defn ^:export main [name]
  (md5 (str "hi" name)))

(main "jinwei")
```

TypeError: Cannot read property 'cljs$core$IFn$_invoke$arity$1' of undefined
    at Object.demo$foo$main [as main] (/Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/demo/foo.cljs:14:4)
    at /Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/demo/foo.cljs:18:1
    at global.SHADOW_IMPORT (/Users/MY_NAME/tmp/shadow-cljs-app/out/script.js:57:44)
    at Object.shadow$cljs$devtools$client$node$closure_import [as closure_import] (/Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:36:4)
    at /Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:109:15
    at /Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:94:23
    at Object.shadow$cljs$devtools$client$node$build_complete [as build_complete] (/Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:107:12)
    at Object.shadow$cljs$devtools$client$node$process_message [as process_message] (/Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:139:6)
    at WebSocket.<anonymous> (/Users/MY_NAME/tmp/shadow-cljs-app/target/shadow-cljs/builds/script/dev/out/cljs-runtime/shadow/cljs/devtools/client/node.cljs:172:16)
    at emitOne (events.js:96:13)
DEVTOOLS: app shutdown demo.foo.stop_BANG_

**Comment by jinwei233** [comment]
after reinstall shadow-cljs, it works now! I don't know what happened. so please close this issue.

**Comment by jiyinyiyong** [comment]
Always use latest version~
