### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'shadow-cljs/builds/ssr/dev/out/cljs-runtime/goog.debug.error.js'

### ISSUE THREAD

**Issue by chenyong** [thheller/shadow-cljs#193]
It should be reproduced if you upgrade `2.1.3` in https://github.com/shadow-cljs/shadow-cljs.org , which currently using `2.1.1`.

It's targeting `:node-script`:

```
:ssr {:target :node-script
                :output-to "target/ssr.js"
                :main app.render/main!
                :devtools {:after-load app.render/main!}}}}
```

```
=>> yarn compile-ssr
yarn run v1.3.2
$ shadow-cljs compile ssr
shadow-cljs - config: /Users/chen/repo/shadow-cljs/shadow-cljs.org/shadow-cljs.edn version: 2.1.3
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - starting ...
[:ssr] Compiling ...
[:ssr] Build completed. (80 files, 59 compiled, 0 warnings, 10.91s)
✨  Done in 30.45s.
=>> yarn html
yarn run v1.3.2
$ node target/ssr.js && cp entry/manifest.json dist/
Error: ENOENT: no such file or directory, open 'shadow-cljs/builds/ssr/dev/out/cljs-runtime/goog.debug.error.js'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at global.SHADOW_IMPORT (/Users/chen/repo/shadow-cljs/shadow-cljs.org/target/ssr.js:45:15)
    at /Users/chen/repo/shadow-cljs/shadow-cljs.org/target/ssr.js:3004:1
    at Object.<anonymous> (/Users/chen/repo/shadow-cljs/shadow-cljs.org/target/ssr.js:3084:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

however the file actually exists:

```
=>> ls target/shadow-cljs/builds/ssr/dev/out/cljs-runtime/goog.debug.error.js
target/shadow-cljs/builds/ssr/dev/out/cljs-runtime/goog.debug.error.js
```

**Comment by thheller** [comment]
Oops. Didn't anticipate `:output-to` in the `target` directory. Fixed in `2.1.4`.
