### ISSUE TITLE
Trouble compiling with latest clojurescript with closure overrides

### ISSUE THREAD

**Issue by levitanong** [thheller/shadow-cljs#225]
Works:
- clojurescript 1.10.191 AND google closure override
- clojurescript 1.10.217 AND NOT google closure override

Breaks:
- clojurescript 1.10.217 AND google closure override

Repro repo: https://github.com/levitanong/closure-repro

Stack trace:
```
Mar 23, 2018 1:52:46 PM clojure.tools.logging$eval1271$fn__1274 invoke
WARNING: failed to handle server msg: {:type :start-autobuild}
java.lang.NoSuchFieldError: STRICT_MISSING_PROPERTIES
	at cljs.closure__init.load(Unknown Source)
	at cljs.closure__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at cljs.repl$loading__5569__auto____6013.invoke(repl.cljc:9)
	at cljs.repl__init.load(Unknown Source)
	at cljs.repl__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at shadow.build.macros$load_macros$fn__13412$fn__13419.invoke(macros.clj:70)
	at shadow.build.macros$load_macros$fn__13412.invoke(macros.clj:69)
	at shadow.build.macros$load_macros.invokeStatic(macros.clj:59)
	at shadow.build.macros$load_macros.invoke(macros.clj:50)
	at shadow.build.compiler$load_cached_cljs_resource.invokeStatic(compiler.clj:495)
	at shadow.build.compiler$load_cached_cljs_resource.invoke(compiler.clj:460)
	at shadow.build.compiler$maybe_compile_cljs.invokeStatic(compiler.clj:617)
	at shadow.build.compiler$maybe_compile_cljs.invoke(compiler.clj:601)
	at shadow.build.compiler$generate_output_for_source.invokeStatic(compiler.clj:671)
	at shadow.build.compiler$generate_output_for_source.invoke(compiler.clj:661)
	at shadow.build.compiler$par_compile_one.invokeStatic(compiler.clj:715)
	at shadow.build.compiler$par_compile_one.invoke(compiler.clj:674)
	at shadow.build.compiler$par_compile_cljs_sources$fn__13682$iter__13683__13687$fn__13688$fn__13689$fn__13690.invoke(compiler.clj:766)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1965)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1965)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$bound_fn_STAR_$fn__5471.doInvoke(core.clj:1995)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by thheller** [comment]
This breaks due to https://github.com/clojure/clojurescript/commit/7779dc4c6a5370e7411884fd1055ab046f794142.

I'll see if we can find a solution upstream in CLJS. This has been very brittle and breaks with pretty much every closure-compiler release. Nothing I can do about it on my end.

**Comment by thheller** [comment]
CLJS updated so this is no longer a problem.
