### ISSUE TITLE
No reader function for tag object

### ISSUE THREAD

**Issue by mjmeintjes** [thheller/shadow-cljs#239]
A similar error to #219 
Using shadow-cljs 2.2.25

Problem seems to be the following data that's included in the output:
```
file #object[java.io.File 0x49491626 "/home/matthys/projects/personal/learning/src/learning/tools/core.cljs"]
```
```
:url #object[java.net.URL 0x478ee17f "file:/home/matthys/projects/personal/learning/src/learning/tools/core.cljs"]
```

```
failed to process message {:type :repl/init, :repl-state {:shadow.cljs.repl/repl-state true,
```
```
 Error: No reader function for tag object.
    at new cljs$core$ExceptionInfo (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/core.cljs:11123:11)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/core.cljs:11150:1)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/core.cljs:11153:16)
    at Function.cljs.tools.reader.impl.errors.throw_ex.cljs$core$IFn$_invoke$arity$variadic (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:37:12)
    at Function.cljs.tools.reader.impl.errors.reader_error.cljs$core$IFn$_invoke$arity$variadic (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:43:4)
    at Object.cljs$tools$reader$impl$errors$throw_unknown_reader_tag [as throw_unknown_reader_tag] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:227:4)
    at cljs$tools$reader$edn$read_tagged (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:374:10)
    at /home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:72:21
    at cljs$tools$reader$edn$read_dispatch (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs.tools.reader.edn.js:118:3)
    at Object.cljs$tools$reader$edn$read_delimited [as read_delimited] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:176:25)
    at cljs$tools$reader$edn$read_map (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:196:17)
    at Object.cljs$tools$reader$edn$read_delimited [as read_delimited] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:176:25)
    at cljs$tools$reader$edn$read_map (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:196:17)
    at Object.cljs$tools$reader$edn$read_delimited [as read_delimited] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:176:25)
    at cljs$tools$reader$edn$read_map (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:196:17)
    at Function.cljs.tools.reader.edn.read.cljs$core$IFn$_invoke$arity$4 (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:411:34)
  message: 'No reader function for tag object.',
  data:
   { meta: null,
     cnt: 2,
     arr: [ [Object], [Object], [Object], [Object] ],
     __hash: null,
     'cljs$lang$protocol_mask$partition0$': 16647951,
     'cljs$lang$protocol_mask$partition1$': 139268 },
  cause: null,
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: No reader function for tag object.\n    at new cljs$core$ExceptionInfo (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/core.cljs:11123:11)\n    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/core.cljs:11150:1)\n    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/core.cljs:11153:16)\n    at Function.cljs.tools.reader.impl.errors.throw_ex.cljs$core$IFn$_invoke$arity$variadic (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:37:12)\n    at Function.cljs.tools.reader.impl.errors.reader_error.cljs$core$IFn$_invoke$arity$variadic (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:43:4)\n    at Object.cljs$tools$reader$impl$errors$throw_unknown_reader_tag [as throw_unknown_reader_tag] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/impl/errors.cljs:227:4)\n    at cljs$tools$reader$edn$read_tagged (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:374:10)\n    at /home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:72:21\n    at cljs$tools$reader$edn$read_dispatch (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs.tools.reader.edn.js:118:3)\n    at Object.cljs$tools$reader$edn$read_delimited [as read_delimited] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:176:25)\n    at cljs$tools$reader$edn$read_map (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:196:17)\n    at Object.cljs$tools$reader$edn$read_delimited [as read_delimited] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:176:25)\n    at cljs$tools$reader$edn$read_map (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:196:17)\n    at Object.cljs$tools$reader$edn$read_delimited [as read_delimited] (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:176:25)\n    at cljs$tools$reader$edn$read_map (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:196:17)\n    at Function.cljs.tools.reader.edn.read.cljs$core$IFn$_invoke$arity$4 (/home/matthys/projects/personal/learning/.shadow-cljs/builds/node/dev/out/cljs-runtime/cljs/tools/reader/edn.cljs:411:34)' }
```

**Comment by thheller** [comment]
I can't seem to reproduce this.

Any more hints on the steps to take to get into this state or does your REPL just start out with this error?

**Comment by mjmeintjes** [comment]
I've added a repo to demonstrate: 
https://github.com/mjmeintjes/shadow-cljs-nodejs-bug

The readme file contains reproduction steps for 2 somewhat related errors I've encountered, error 2 is the one mentioned here. Unfortunately I've only been able to test this using Cider, so not sure if the same problem will occur with Cursive.

It seems to be related to `reload-namespaces` in the `repl-require` fn inside node.cljs sometimes being nil, which throws an error and sets the shadow-cljs server into an error state.

Please let me know if anything is unclear.

**Comment by mjmeintjes** [comment]
The following seems to have fixed the issue for me (added to the `repl-require` fn in node.cljs):
```
(or (not (is-loaded? output-name))
                (and reload-namespaces
                     (some reload-namespaces provides)))
```
