### ISSUE TITLE
Browser hangs when (re)loading animations?

### ISSUE THREAD

**Issue by alex-dixon** [thheller/shadow-cljs#254]
The browser freezes up when changing the number of animated items in this list from 10 to 15:
https://github.com/alex-dixon/shadow-cljs-react-spring/blob/03b2859bff2b4d19b162c94046e3076f470aec7c/src/main/demo/app.cljs#L19

It will load fine with 10 items, but not when the number of items is 100. 

There's a Google Chrome Helper that shows ~200% CPU in macOS activity monitor. Killing it let me close the tab.

I'm not positive animation has anything to do with it...I just haven't had this problem with other examples. I also haven't tried this in JS, so the initial loading with 100 may not be a bug, but refreshing with ~10 seems like it could be.

**Comment by thheller** [comment]
Good example showing why I don't like `reagent`. It is extremely inefficient when running in tight loops such as animations. I'm sure you can make it more efficient but I don't know enough about `reagent` to make any suggestions.

Looks like this https://github.com/alex-dixon/shadow-cljs-react-spring/blob/03b2859bff2b4d19b162c94046e3076f470aec7c/src/main/demo/app.cljs#L15 should only be done once statically. Not in a function that gets called once per render.

Definitely not related to `shadow-cljs` though.

**Comment by alex-dixon** [comment]
Getting this error when printing to the console on each render:
```
[2018-04-22 07:48:07 - ERROR] XNIO001007: A channel event liste
ner threw an exception
java.lang.AssertionError: Assert failed: No more than 1024 pend
ing puts are allowed on a single channel. Consider using a wind
owed buffer.
(< (.size puts) impl/MAX-QUEUE-SIZE)
        at clojure.core.async.impl.channels.ManyToManyChannel.p
ut_BANG_(channels.clj:152)
        at clojure.core.async$put_BANG_.invokeStatic(async.clj:
164)
        at clojure.core.async$put_BANG_.invoke(async.clj:157)
        at shadow.undertow$websocket$reify__22188$handler_fn__2
2189.invoke(undertow.clj:72)
        at shadow.undertow.WsTextReceiver.onFullTextMessage(WsT
extReceiver.java:20)
        at io.undertow.websockets.core.AbstractReceiveListener$
2.complete(AbstractReceiveListener.java:156)
        at io.undertow.websockets.core.AbstractReceiveListener$
2.complete(AbstractReceiveListener.java:152)
        at io.undertow.websockets.core.BufferedTextMessage.read
(BufferedTextMessage.java:105)
        at io.undertow.websockets.core.AbstractReceiveListener.
readBufferedText(AbstractReceiveListener.java:152)
        at io.undertow.websockets.core.AbstractReceiveListener.
bufferFullMessage(AbstractReceiveListener.java:90)
        at io.undertow.websockets.core.AbstractReceiveListener.
onText(AbstractReceiveListener.java:70)
        at io.undertow.websockets.core.AbstractReceiveListener.
handleEvent(AbstractReceiveListener.java:44)
        at io.undertow.websockets.core.AbstractReceiveListener.
handleEvent(AbstractReceiveListener.java:33)
        at org.xnio.ChannelListeners.invokeChannelListener(Chan
nelListeners.java:92)
        at io.undertow.server.protocol.framed.AbstractFramedCha
nnel$FrameReadListener.handleEvent(AbstractFramedChannel.java:9
42)
        at io.undertow.server.protocol.framed.AbstractFramedCha
nnel$FrameReadListener.handleEvent(AbstractFramedChannel.java:9
23)
        at org.xnio.ChannelListeners.invokeChannelListener(Chan
nelListeners.java:92)
        at io.undertow.server.protocol.framed.AbstractFramedCha
nnel$FrameReadListener$1.run(AbstractFramedChannel.java:949)
        at io.undertow.server.protocol.framed.AbstractFramedCha
nnel$3.run(AbstractFramedChannel.java:230)
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:
582)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
```
