### ISSUE TITLE
Cannot set property 'Error' with :optimizations :whitespace

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#344]
Hi all and Thomas (2x today) !

I have an odd thing happening with this build configuration:

```clojure
{:target :node-script
 :main cd.create-publish-pipeline/-main
 :output-to "bin/create-publish-pipeline"
 :devtools {:autoload false}
 :release {:compiler-options {:optimizations :whitespace}}}
```

This error is thrown when I launch the script with `bin/create-publish-pipeline`:

```
goog.nodeGlobalRequire=function(path){return false};goog.provide("goog.debug.Error");goog.debug.Error=function(opt_msg){if(Error.captureStackTrace)Error.captureStackTrace(this,goog.debug.Error);else{var stack=(new Error).stack;if(stack)this.stack=stack}if(opt_msg)this.message=String(opt_msg);this.reportErrorToServer=true};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.provide("goog.dom.NodeType");goog.dom.NodeType={ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,ENTITY_REFERENCE:5,ENTITY:6,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9,DOCUMENT_TYPE:10,DOCUMENT_FRAGMENT:11,NOTATION:12};goog.provide("goog.string");goog.provide("goog.string.Unicode");goog.define("goog.string.DETECT_DOUBLE_ESCAPING",false);goog.define("goog.string.FORCE_NON_DOM_HTML_UNESCAPING",false);goog.string.Unicode={NBSP:" "};goog.string.startsWith=function(str,prefix){return str.lastIndexOf(prefix,0)==0};goog.string.ends

TypeError: Cannot set property 'Error' of undefined
    at /home/arichiardi/git/laputa/continuous-delivery/bin/create-publish-pipeline:69:102
    at Object.<anonymous> (/home/arichiardi/git/laputa/continuous-delivery/bin/create-publish-pipeline:3038:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

If I take away `:optimizations` it does not happen and the script executes fine.

**Comment by thheller** [comment]
`:whitespace` leaves `goog.provide` and `goog.require` calls and `goog.provide("goog.debug.Error")` should create the `goog.debug.Error` but does so in the module local scope which is not correct.

Just don't use `:whitespace` its pointless anyways.
