### ISSUE TITLE
Error running cli: `Cannot find anything to run for: shadow.cljs.devtools.cli/once`

### ISSUE THREAD

**Issue by dvingo** [thheller/shadow-cljs#36]
I'm trying to play around with the project. I get the following error when attempting to run devtools cli:
```
Exception in thread "main" java.lang.Exception: Cannot find anything to run for: shadow.cljs.devtools.cli/once, compiling:(/tmp/form-init2146566662431793486.clj:1:73)
        at clojure.lang.Compiler.load(Compiler.java:7469)
        at clojure.lang.Compiler.loadFile(Compiler.java:7395)
        at clojure.main$load_script.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invokeStatic(main.clj:279)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invokeStatic(main.clj:310)
        at clojure.main$null_opt.invokeStatic(main.clj:344)
        at clojure.main$null_opt.invoke(main.clj:341)
        at clojure.main$main.invokeStatic(main.clj:423)
        at clojure.main$main.doInvoke(main.clj:386)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Cannot find anything to run for: shadow.cljs.devtools.cli/once
        at user$eval137.invokeStatic(form-init2146566662431793486.clj:1)
        at user$eval137.invoke(form-init2146566662431793486.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7005)
        at clojure.lang.Compiler.eval(Compiler.java:6995)
        at clojure.lang.Compiler.load(Compiler.java:7457)
        ... 12 more
```
This is the command I ran:
```bash
lein run -m shadow.cljs.devtools.cli/once app
```
Here are the steps I took, I started from a fresh line template:

```bash
lein new app cl
```

edit `project.clj` to look like:

```clojure
(defproject cl "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies
  [[org.clojure/clojure "1.9.0-alpha17"]
  [thheller/shadow-devtools "1.0.20170516"]]
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

Create `shadow-cljs.edn` file:

```clojure
[{
  :id :app
  :target :browser
  :public-dir "public/js"
  :public-path "/js"
  :modules
  {:main {:entries [cl.core]}}
}]
```

Rename `src/cl/core.clj` => `src/cl/core.cljs`

with these contents:

```clojure
(ns cl.core)
(defn hello [] "hi there")
```

Add `resources/public/index.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script src="/js/main.js"></script>
  </body>
</html>
```

run:

```bash
lein run -m shadow.cljs.devtools.cli/once app
```

If I run the command with just the namespace, then I get the help output:

```bash
$ lein run -m shadow.cljs.devtools.cli
Please use specify a build or use --npm
Command line args:
-----
  -b, --build BUILD-ID             use build defined in shadow-cljs.edn
      --dev                        compile once and watch
      --once                       compile once and exit
      --release                    compile in release mode and exit
      --debug                      debug mode, useful in combo with --release (pseudo-names, source-map)
      --npm                        run in npm compatibility mode
      --runtime TARGET      :node  (npm-only) node or browser
  -e, --entries NAMESPACES         (npm-only) comma seperated list of CLJS entry namespaces
  -v, --verbose
  -h, --help
-----
```

**Comment by thheller** [comment]
Ooops, I accidentally removed all those when rebuilding the CLI without changing the docs.

The new style actually parses the CLI args properly.
```
lein run -m shadow.cljs.devtools.cli --build app --once
```

If you have `npm` or `yarn` installed you can also try `npm install -g shadow-cljs` and then just run `shadow-cljs` in your project directory. It doesn't need the `project.cli` then.

If you prefer `lein` the `project.clj` needs to be updated

```
(defproject cl "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies
  [[org.clojure/clojure "1.9.0-alpha17"]
  [thheller/shadow-cljs "1.0.20170531"]]
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

I renamed everything from `shadow-devtools` to `shadow-cljs` few weeks ago but haven't updated all doc references I guess.

**Comment by dvingo** [comment]
No worries! I updated dep and the cli is working! Thanks so much :)
