### ISSUE TITLE
Exception in thread "main" java.lang.AssertionError: Assert failed: (qualified-symbol? sym)

### ISSUE THREAD

**Issue by yqrashawn** [thheller/shadow-cljs#366]
error when running `shadow-cljs watch app`, already solved on on [slack](https://clojurians.slack.com/messages/C6N245JGG/), put it here in case anybody encounter this later.

error message:
```
Exception in thread "main" java.lang.AssertionError: Assert failed: (qualified-symbol? sym)
        at shadow.cljs.devtools.server.nrepl04$middleware_load.invokeStatic(nrepl04.clj:269)
        at shadow.cljs.devtools.server.nrepl04$middleware_load.invoke(nrepl04.clj:269)
        at clojure.core$map$fn__5587.invoke(core.clj:2745)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:528)
        at clojure.core$seq__5124.invokeStatic(core.clj:137)
        at clojure.core$filter$fn__5614.invoke(core.clj:2801)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:528)
        at clojure.core$seq__5124.invokeStatic(core.clj:137)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
        at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6748)
        at clojure.core$into.invokeStatic(core.clj:6815)
        at clojure.core$into.invoke(core.clj:6807)
```

`shadow-cljs.edn`:

```
{:nrepl {:port 9898
         :middleware [[cider/piggieback "0.3.5"]]}
 :http {:port 3333
        :host "0.0.0.0"}
 :source-paths ["src/clj" "src/cljs"]
 :dependencies [[org.clojure/clojure "1.8.0"]
                [org.clojure/clojurescript "1.10.238"]
                [reagent "0.7.0"]
                [re-frame "0.10.5"]
                ;; [secretary "1.2.3"]
                [garden "1.3.5"]
                [ns-tracker "0.3.1"]
                [compojure "1.5.0"]
                [bidi "2.1.3"]
                [yogthos/config "0.8"]
                [ring "1.4.0"]
                [re-pressed "0.2.2"]
                [re-frisk "0.5.3"]
                [binaryage/devtools "0.9.10"]
                [day8.re-frame/re-frame-10x "0.3.3"]]

 :builds
 {:app {:target :browser
        :output-dir "resources/public/js/compiled/"
        :asset-path           "js/compiled/out"
        :modules {:main {:entries [right-site.core]}}
        :devtools {:http-root "resources/public"
                   :http-port 3000
                   :http-host "0.0.0.0"
                   :open-file-command ["emacsclient" "-n" ["+%s:%s" :line :column] :file]
                   :autoload true}}}}
```

**Comment by yqrashawn** [comment]
The error went away after I remove `:middleware [[cider/piggieback "0.3.5"]]`.

seems shadow-cljs provides it's own version of piggieback https://github.com/thheller/shadow-cljs/commit/01bbbdd91d27e6d1f2a72acc7707918d32f42e74
