### ISSUE TITLE
Shadow CLJS dies on launch with java.lang.NoSuchFieldError: PARSE_RESULTS

### ISSUE THREAD

**Issue by gnl** [thheller/shadow-cljs#460]
Launching shadow-cljs 2.7.7 and 2.8.15 with `shadow-cljs server` results in the exception below. 2.7.6 works fine.

```
❯ shadow-cljs server                                                                                                                                                             1s 405ms
shadow-cljs - config: /Users/gnl/Code/re-frame-playground/shadow-cljs.edn  cli version: 2.8.15  node: v10.15.2
shadow-cljs - running: lein with-profile +shadow run -m shadow.cljs.devtools.cli --npm server
Exception in thread "main" java.lang.NoSuchFieldError: PARSE_RESULTS, compiling:(/private/var/folders/s8/nlv_xvqn2_91m_fgd1tdxkl80000gn/T/form-init7447016524861973501.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoSuchFieldError: PARSE_RESULTS
	at shadow.build.closure.JsInspector.getFileInfo(JsInspector.java:161)
	at shadow.build.closure.JsInspector.getFileInfoMap(JsInspector.java:173)
	at shadow.build.classpath$inspect_js.invokeStatic(classpath.clj:96)
	at shadow.build.classpath$inspect_js.invoke(classpath.clj:74)
	at shadow.build.classpath$inspect_resource.invokeStatic(classpath.clj:222)
	at shadow.build.classpath$inspect_resource.invoke(classpath.clj:218)
	at shadow.build.classpath$inspect_resources$fn__10814.invoke(classpath.clj:527)
	at clojure.core$map$fn__5587.invoke(core.clj:2745)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$filter$fn__5614.invoke(core.clj:2801)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$map$fn__5587.invoke(core.clj:2738)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$into.invokeStatic(core.clj:6815)
	at clojure.core$into.invoke(core.clj:6807)
	at shadow.build.classpath$inspect_resources.invokeStatic(classpath.clj:543)
	at shadow.build.classpath$inspect_resources.invoke(classpath.clj:522)
	at shadow.build.classpath$process_root_contents.invokeStatic(classpath.clj:551)
	at shadow.build.classpath$process_root_contents.invoke(classpath.clj:546)
	at shadow.build.classpath$find_jar_resources.invokeStatic(classpath.clj:580)
	at shadow.build.classpath$find_jar_resources.invoke(classpath.clj:553)
	at shadow.build.classpath$find_resources.invokeStatic(classpath.clj:633)
	at shadow.build.classpath$find_resources.invoke(classpath.clj:625)
	at shadow.build.classpath$index_path_STAR_.invokeStatic(classpath.clj:864)
	at shadow.build.classpath$index_path_STAR_.invoke(classpath.clj:861)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$reduce.invoke(core.clj:6730)
	at shadow.build.classpath$index_classpath$fn__10963$fn__10964.invoke(classpath.clj:983)
	at clojure.lang.Atom.swap(Atom.java:37)
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2344)
	at clojure.core$swap_BANG_.invoke(core.clj:2337)
	at shadow.build.classpath$index_classpath$fn__10963.invoke(classpath.clj:983)
	at shadow.build.classpath$index_classpath.invokeStatic(classpath.clj:982)
	at shadow.build.classpath$index_classpath.invoke(classpath.clj:977)
	at shadow.build.classpath$index_classpath.invokeStatic(classpath.clj:979)
	at shadow.build.classpath$index_classpath.invoke(classpath.clj:977)
	at shadow.cljs.devtools.server.common$fn__15612.invokeStatic(common.clj:89)
	at shadow.cljs.devtools.server.common$fn__15612.invoke(common.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at shadow.runtime.services$start_one.invokeStatic(services.clj:98)
	at shadow.runtime.services$start_one.invoke(services.clj:87)
	at shadow.runtime.services$start_many$fn__9527.invoke(services.clj:127)
	at shadow.runtime.services$start_many.invokeStatic(services.clj:126)
	at shadow.runtime.services$start_many.invoke(services.clj:105)
	at shadow.runtime.services$start_all.invokeStatic(services.clj:144)
	at shadow.runtime.services$start_all.invoke(services.clj:139)
	at shadow.cljs.devtools.server$start_system.invokeStatic(server.clj:369)
	at shadow.cljs.devtools.server$start_system.invoke(server.clj:241)
	at shadow.cljs.devtools.server$start_BANG_.invokeStatic(server.clj:485)
	at shadow.cljs.devtools.server$start_BANG_.invoke(server.clj:408)
	at shadow.cljs.devtools.server$start_BANG_.invokeStatic(server.clj:411)
	at shadow.cljs.devtools.server$start_BANG_.invoke(server.clj:408)
	at shadow.cljs.devtools.server$from_cli.invokeStatic(server.clj:617)
	at shadow.cljs.devtools.server$from_cli.invoke(server.clj:593)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at shadow.cljs.devtools.cli$lazy_invoke.invokeStatic(cli.clj:24)
	at shadow.cljs.devtools.cli$lazy_invoke.doInvoke(cli.clj:21)
	at clojure.lang.RestFn.invoke(RestFn.java:460)
	at shadow.cljs.devtools.cli$blocking_action.invokeStatic(cli.clj:131)
	at shadow.cljs.devtools.cli$blocking_action.invoke(cli.clj:118)
	at shadow.cljs.devtools.cli$main.invokeStatic(cli.clj:179)
	at shadow.cljs.devtools.cli$main.doInvoke(cli.clj:134)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$apply.invoke(core.clj:652)
	at shadow.cljs.devtools.cli$_main.invokeStatic(cli.clj:221)
	at shadow.cljs.devtools.cli$_main.doInvoke(cli.clj:219)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:385)
	at user$eval149.invokeStatic(form-init7447016524861973501.clj:1)
	at user$eval149.invoke(form-init7447016524861973501.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
```

Here's shadow-cljs.edn:

```
{:lein
 {:profile "+shadow"}

 :open-file-command
 ["idea" :pwd "--line" :line :file]

 :builds
 {:ghostwheel {:target           :browser
               :devtools         {:after-load-async ghostwheel.core/after-check-async
                                  :preloads         [devtools.preload]}
               :output-dir       "public/js"
               :asset-path       "/js"
               :modules          {:ghostwheel {:entries [re-frame-playground.ghostwheel]}}
               :compiler-options {:optimizations :simple}
               :dev              {:compiler-options {:external-config {:ghostwheel {}}}}
```

...and project.clj:

```
(defproject re-frame-playground "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.439"]
                 [gnl/ghostwheel.tracer "0.3.5"]
                 [gnl/ghostwheel "0.3.5"]]
  :source-paths ["src"
                 "checkouts/ghostwheel/src"
                 "checkouts/ghostwheel.unghost/src"
                 "checkouts/ghostwheel.specs/src"
                 "checkouts/ghostwheel.logging/src"
                 "checkouts/ghostwheel.tracer/src"]
  :clean-targets ^{:protect false} ["public/js" "resources/public/js" "public/css" "test/js" "target" "out" ".shadow-cljs" ".cpcache"]
  :profiles {:shadow {:dependencies [[thheller/shadow-cljs "2.8.15"]]}})
```

**Comment by thheller** [comment]
This is caused by an incorrect closure-compiler dependency and you are also using an incorrect clojurescript version.

Should be
```
[org.clojure/clojurescript "1.10.520"]
[com.google.javascript/closure-compiler-unshaded "v20190121"]
```

**Comment by gnl** [comment]
Bumping the ClojureScript version and explicitly adding the closure-compiler-unshaded dependency did the trick, thank you! Although I wasn't directly depending on closure-compiler-unshaded at all so I don't know why the correct version isn't used by default.

**Comment by thheller** [comment]
`lein` doesn't resolve dependency version conflicts so whatever comes first is used. In your case `clojurescript` is listed first so its `closure-compiler-unshaded` version is used as well.
