### ISSUE TITLE
internal server error for WebSockets

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#50]
Never saw this error before. Tried, it happened in `0.9.6` and `0.9.7`.

```
$ shadow-cljs -b dev --dev
shadow-cljs - 1.0.20170615 using /Users/chen/repo/cirru/stack-editor/shadow-cljs.edn
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - optimizing startup
shadow-cljs - starting ...
[:dev] Configuring build.
[:dev] Compiling ...
[:dev] Build completed. (194 files, 92 compiled, 0 warnings, 20.30s)
[0:0] cljs.user=> Jun 15, 2017 2:23:52 PM aleph.http.server invoke
SEVERE: error in HTTP handler
java.lang.NullPointerException
	at java.util.UUID.fromString(UUID.java:192)
	at shadow.cljs.devtools.server.worker.ws$process.invokeStatic(ws.clj:201)
	at shadow.cljs.devtools.server.worker.ws$process.invoke(ws.clj:189)
	at shadow.cljs.devtools.api$web_root.invokeStatic(api.clj:30)
	at shadow.cljs.devtools.api$web_root.invoke(api.clj:23)
	at shadow.cljs.devtools.api$get_ring_handler$fn__20083.invoke(api.clj:44)
	at aleph.http.server$handle_request$fn__17506$f__12968__auto____17507.invoke(server.clj:156)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__12860$f__12861.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```
![image](https://user-images.githubusercontent.com/449224/27168055-8ae1ecee-5169-11e7-90b9-68022fe67d13.png)

part of my config, currently using `-b dev`

```edn
{
 :builds {:dev {:output-dir "target/browser"
                :asset-path "/browser"
                :target :browser
                :modules {:main {:entries [app.main]}}}
          :npm {:output-dir "target"
                :target :npm-module}
          :release {:entries [app.main]
                    :target :npm-module
                    :output-dir "target/release/"}}}
```

**Comment by thheller** [comment]
I should not make releases at 01:00, I accidentally broke non-server mode. I'll fix that first thing.

**Comment by thheller** [comment]
Should be fixed in `[thheller/shadow-cljs "1.0.20170615-09"]` and `shadow-cljs@0.9.8`.

**Comment by jiyinyiyong** [comment]
Confirmed~

**Comment by jiyinyiyong** [comment]
oh, no...
```
$ shadow-cljs -b dev --dev
shadow-cljs - 1.0.20170615-09 using /Users/chen/repo/cirru/stack-editor/shadow-cljs.edn
shadow-cljs - starting ...
[:dev] Configuring build.
[:dev] Compiling ...
[:dev] Build completed. (194 files, 1 compiled, 0 warnings, 2.82s)
[0:0] cljs.user=> Jun 15, 2017 3:19:03 PM aleph.http.server invoke
SEVERE: error in HTTP handler
java.lang.NullPointerException
	at java.util.UUID.fromString(UUID.java:192)
	at shadow.cljs.devtools.server.worker.ws$process.invokeStatic(ws.clj:201)
	at shadow.cljs.devtools.server.worker.ws$process.invoke(ws.clj:189)
	at shadow.cljs.devtools.api$web_root.invokeStatic(api.clj:30)
	at shadow.cljs.devtools.api$web_root.invoke(api.clj:23)
	at shadow.cljs.devtools.api$get_ring_handler$fn__20083.invoke(api.clj:44)
	at aleph.http.server$handle_request$fn__17506$f__12968__auto____17507.invoke(server.clj:156)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__12860$f__12861.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thheller** [comment]
Hmm, that is with webpack? Maybe an old version?

**Comment by jiyinyiyong** [comment]
I remove whole `target/`. It does not throw error now. So, that was affected by caches?

**Comment by thheller** [comment]
I guess.

Not really sure what could cause that as the cache should have been invalidated just by upgrading to a new version. You don't load the build output directly but use webpack to bundle it first correct? Maybe webpack was confused about something.

I'll investigate further if it happens again.

**Comment by jiyinyiyong** [comment]
I was bundling it with Webpack, but troubled by the lack of SourceMaps. So I tried to load code compiled with `:target :browser`. Then I saw this error. Meanwhile Webpack did not throw any error.

**Comment by thheller** [comment]
Thats even weirder. It would be great if you could zip up your `target` folder and send it to me if it happens again, definitely don't just delete everything. I don't want `delete your cache folder` to become a thing. I'd rather just fix caching.

**Comment by jiyinyiyong** [comment]
okay, will do if I see such errors again.

**Comment by jiyinyiyong** [comment]
My laptop at home is using old shadow-cljs, and files in `target/` is not removed. I saw the error again. Got a zip file here: https://drive.google.com/file/d/0BzNUiG02rjc9ZE1yRGRRWUN6VTg/view?usp=sharing

**Comment by thheller** [comment]
Thanks, I'll take a look.
