### ISSUE TITLE
java.io.IOException: No such file or directory, compiling:(shadow/cljs/devtools/cli.clj:1:1)

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#56]
I think it's a problem in `0.11.0`, I switched back to `0.10.0` and it work again.

```bas
# calling from npm script
$ shadow-cljs --build release --release
shadow-cljs - config: /Users/chen/repo/respo/respo/shadow-cljs.edn version: 1.0.20170618
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - starting ...
Exception in thread "main" java.io.IOException: No such file or directory, compiling:(shadow/cljs/devtools/cli.clj:1:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6953)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler.analyze(Compiler.java:6685)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6056)
	at clojure.lang.Compiler$TryExpr$Parser.parse(Compiler.java:2290)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6946)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler.analyze(Compiler.java:6685)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6056)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5428)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3993)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6944)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6934)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler.analyze(Compiler.java:6685)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3787)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6948)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler.analyze(Compiler.java:6685)
	at clojure.lang.Compiler.compile1(Compiler.java:7547)
	at clojure.lang.Compiler.compile1(Compiler.java:7542)
	at clojure.lang.Compiler.compile(Compiler.java:7619)
	at clojure.lang.RT.compile(RT.java:408)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__6368.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$compile$fn__6373.invoke(core.clj:6018)
	at clojure.core$compile.invokeStatic(core.clj:6018)
	at clojure.core$compile.invoke(core.clj:6010)
	at user$eval133.invokeStatic(NO_SOURCE_FILE:1)
	at user$eval133.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:7005)
	at clojure.lang.Compiler.eval(Compiler.java:6994)
	at clojure.lang.Compiler.eval(Compiler.java:6968)
	at clojure.core$eval.invokeStatic(core.clj:3194)
	at clojure.main$eval_opt.invokeStatic(main.clj:290)
	at clojure.main$eval_opt.invoke(main.clj:284)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$main_opt.invokeStatic(main.clj:316)
	at clojure.main$main_opt.invoke(main.clj:312)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at clojure.lang.Compiler.writeClassFile(Compiler.java:7493)
	at clojure.core$gen_class.invokeStatic(genclass.clj:638)
	at clojure.core$gen_class.doInvoke(genclass.clj:507)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6855)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6932)
	... 49 more
```

Also I noticed `--server` & `--repl` does not work correctly as `0.10.0`. But not very sure.

**Comment by thheller** [comment]
Weird, probably related to #55.

I should have a new release ready soon which hopefully fixes that.

**Comment by jiyinyiyong** [comment]
Maybe not. I saw @gfZeng got this error message too, he just installed it.

**Comment by thheller** [comment]
It is weird since `shadow-cljs` isn't even anywhere on the stack. It is definitely the AOT compile, can't tell what is wrong yet. It works for me.

**Comment by jiyinyiyong** [comment]
Tried again and works now in `0.11.0`. At first my project was running `0.9`, and I upgraded to `0.11`, it threw this exception, then I downgraded to `0.10` and it worked again. Not sure about when I removed `target/`. Guess you are right about that.

**Comment by jiyinyiyong** [comment]
I can reproduce the problem at current, try `yarn && yarn server` on this project:

https://github.com/minimal-xyz/minimal-shadow-cljs-server

**Comment by thheller** [comment]
Thanks, I can reproduce locally now. Will look into it.

**Comment by thheller** [comment]
I just pushed `shadow-cljs@0.12.0` which includes the fix for this. It also includes the new CLI structure described in #52. `--server` is now just `server`.

**Comment by theronic** [comment]
I'm seeing the same error using shadow-cljs  v2.8.64  node: v12.11.1.

Tried `yarn add global shadow-cljs` and `yarn add shadow-cljs --dev`.

**Comment by thheller** [comment]
@theronic please post the full error you are seeing.

If you use `:lein` with `project.clj` you may have forgotten to put the `thheller/shadow-cljs` dependency into the `:dependencies` in `project.clj`.

Same goes for `:deps` with `deps.edn`.

If you just use `shadow-cljs.edn` it should be pretty much impossible to get this error?

**Comment by theronic** [comment]
Thanks, fixed by adding shadow-cljs under :deps.
And yes, there is a pre-existing project.clj file in the folder. I imagine this might trip a lot of people up who are trying to migrate away from project.clj to shadow-cljs.
