### ISSUE TITLE
Error importing three.js jsm module.

### ISSUE THREAD

**Issue by bbss** [thheller/shadow-cljs#579]
I'm trying to import a jsm module from the webGL library three.js. This fails with an error

Reproducable with new project:
```
yarn add three

shadow-cljs watch buildname

src/core.cljs:
(ns core
  (:require ["three/examples/jsm/loaders/GLTFLoader" :refer [GLTFLoader]]))
```

Stacktrace
```
[:main] Compiling ...
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'babel-core'
Require stack:
- /Users/baruchberger/threetest/.shadow-cljs/babel-worker/babel-worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /Users/baruchberger/threetest/.shadow-cljs/babel-worker/babel-worker.js:399:229
    at Object.<anonymous> (/Users/baruchberger/threetest/.shadow-cljs/babel-worker/babel-worker.js:404:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/baruchberger/threetest/.shadow-cljs/babel-worker/babel-worker.js'
  ]
}
... snip three.js source string...
IOException Stream closed
	java.lang.ProcessBuilder$NullOutputStream.write (ProcessBuilder.java:442)
	java.io.OutputStream.write (OutputStream.java:157)
	java.io.BufferedOutputStream.write (BufferedOutputStream.java:123)
	sun.nio.cs.StreamEncoder.writeBytes (StreamEncoder.java:233)
	sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:303)
	sun.nio.cs.StreamEncoder.implWrite (StreamEncoder.java:281)
	sun.nio.cs.StreamEncoder.write (StreamEncoder.java:125)
	java.io.OutputStreamWriter.write (OutputStreamWriter.java:211)
	java.io.BufferedWriter.flushBuffer (BufferedWriter.java:120)
	java.io.BufferedWriter.write (BufferedWriter.java:233)
	java.io.Writer.write (Writer.java:249)
	jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
[:main] Build failure:
babel failed?
{:file "/Users/baruchberger/threetest/node_modules/three/build/three.module.js"}
ExceptionInfo: babel failed?
	shadow.build.babel/convert-source/fn--11218 (babel.clj:165)
	shadow.build.babel/convert-source (babel.clj:157)
	shadow.build.babel/convert-source (babel.clj:153)
	shadow.build.resolve/make-babel-source-fn/fn--11288 (resolve.clj:184)
	shadow.build.data/get-source-code (data.clj:309)
	shadow.build.data/get-source-code (data.clj:296)
	shadow.build.closure/convert-sources-simple*/iter--10926--10930/fn--10931/fn--10932 (closure.clj:1707)
	shadow.build.closure/convert-sources-simple*/iter--10926--10930/fn--10931 (closure.clj:1706)
	clojure.lang.LazySeq.sval (LazySeq.java:42)
	clojure.lang.LazySeq.seq (LazySeq.java:51)
	clojure.lang.RT.seq (RT.java:535)
	clojure.core/seq--5402 (core.clj:137)
	clojure.core.protocols/seq-reduce (protocols.clj:24)
	clojure.core.protocols/fn--8146 (protocols.clj:75)
	clojure.core.protocols/fn--8146 (protocols.clj:75)
	clojure.core.protocols/fn--8088/G--8083--8101 (protocols.clj:13)
	clojure.core/reduce (core.clj:6828)
	clojure.core/into (core.clj:6895)
	clojure.core/into (core.clj:6887)
	shadow.build.closure/convert-sources-simple* (closure.clj:1735)
	shadow.build.closure/convert-sources-simple* (closure.clj:1702)
	shadow.build.closure/convert-sources-simple (closure.clj:1988)
	shadow.build.closure/convert-sources-simple (closure.clj:1940)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1082)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1075)
	shadow.build.compiler/compile-all (compiler.clj:1333)
	shadow.build.compiler/compile-all (compiler.clj:1194)
	shadow.build.api/compile-sources (api.clj:256)
	shadow.build.api/compile-sources (api.clj:248)
	shadow.build/compile (build.clj:397)
	shadow.build/compile (build.clj:388)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:314)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:300)
	shadow.cljs.devtools.server.worker.impl/do-resource-update (impl.clj:936)
	shadow.cljs.devtools.server.worker.impl/do-resource-update (impl.clj:899)
	shadow.cljs.devtools.server.util/server-thread/fn--13135/fn--13136/fn--13144 (util.clj:285)
	shadow.cljs.devtools.server.util/server-thread/fn--13135/fn--13136 (util.clj:284)
	shadow.cljs.devtools.server.util/server-thread/fn--13135 (util.clj:257)
	java.lang.Thread.run (Thread.java:834)

**Comment by thheller** [comment]
I just tested this locally and it compiles and loads fine? Which version of `shadow-cljs` did you use?

**Comment by bbss** [comment]
I was using 2.8.64, test project also compiled with upgrading global and adding 2.8.67 to npm deps. Then still had some trouble with a different project that still required 2.8.64 in a deps.edn profile, but that's solved as well now! 

Thanks!

**Comment by plexus** [comment]
To anyone else ending up here after googling for "shadow-cljs babel failed", make sure shadow can find your `node` executable.

**Comment by mjmeintjes** [comment]
I also ran into this issue today - I'm running shadow-cljs inside a docker image, and discovered I don't have node installed. Would it be worth adding a check whether node exists?
