### ISSUE TITLE
ReferenceError: shadow$provide is not defined

### ISSUE THREAD

**Issue by gdw2** [thheller/shadow-cljs#583]
Below is a minimal example showing a bug with the **npm-module target**.  Running `global.shadow$provide = {}` from the node repl before 'requiring' eliminates the error.  Additional (short lived?) context [found here](https://clojurians.slack.com/archives/C6N245JGG/p1572360793137900).

```
$ cat shadow-cljs.edn
;; shadow-cljs configuration
{:source-paths ["src" ]
 :dependencies []
 :builds {:app {:target :npm-module :runtime :node :output-dir "node_modules/shadow-cljs" :entries [hi]}}
}

$ cat src/hello.js
module.exports = { name: "Bob" }
$ cat src/hi.cljs
(ns hi
 (:require ["./hello" :as hello])
)

(defn foo []
 (println "hello" hello/name))

$ npx shadow-cljs compile app
shadow-cljs - config: /home/gwarner/code/shadow-test/shadow-cljs.edn  cli version: 2.8.67  node: v10.15.3
[:app] Compiling ...
[:app] Build completed. (23 files, 0 compiled, 0 warnings, 5.65s)

$ node
> hi = require('shadow-cljs/hi')
ReferenceError: shadow$provide is not defined
    at Object.<anonymous> (/home/gwarner/code/shadow-test/node_modules/shadow-cljs/module$hello.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by thheller** [comment]
Can't remember why I closed this.
