### ISSUE TITLE
Invalid core.async blocking call

### ISSUE THREAD

**Issue by RickMoynihan** [thheller/shadow-cljs#592]
Apps that depend on the latest core.async 0.5.527 (released 3 days ago) will now get an error when running with the new `-Dclojure.core.async.go-checking=true` property.

This new feature of core.async is there to help find potential core.async code that may cause deadlocks.  

Enabling this in my app led me to find the following issue inside shadow-cljs.  

It is I believe due to shadow-cljs making an invalid blocking call inside a go block [here](https://github.com/thheller/shadow-cljs/blob/43050cf14338236a30d823a247e51e8cdf1a51ec/src/main/shadow/cljs/devtools/server/system_bus.clj#L36)

It occured in my app when running:

```
$ shadow-cljs watch my-app

Exception in thread "async-dispatch-1" java.lang.IllegalStateException: Invalid blocking call in dispatch thread
	at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invokeStatic(dispatch.clj:29)
	at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invoke(dispatch.clj:26)
	at clojure.core.async$fn__6923.invokeStatic(async.clj:164)
	at clojure.core.async$fn__6923.invoke(async.clj:164)
	at shadow.cljs.devtools.server.system_bus$publish_BANG_.invokeStatic(system_bus.clj:36)
	at shadow.cljs.devtools.server.system_bus$publish_BANG_.invoke(system_bus.clj:32)
	at shadow.cljs.devtools.server.supervisor$start_worker$fn__15727$state_machine__6772__auto____15770$fn__15772.invoke(supervisor.clj:57)
	at shadow.cljs.devtools.server.supervisor$start_worker$fn__15727$state_machine__6772__auto____15770.invoke(supervisor.clj:56)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__6790.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__1684.invoke(channels.clj:265)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__1488$fn__1489.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "async-dispatch-2" java.lang.IllegalStateException: Invalid blocking call in dispatch thread
	at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invokeStatic(dispatch.clj:29)
	at clojure.core.async.impl.dispatch$check_blocking_in_dispatch.invoke(dispatch.clj:26)
	at clojure.core.async$fn__6923.invokeStatic(async.clj:164)
	at clojure.core.async$fn__6923.invoke(async.clj:164)
	at shadow.cljs.devtools.server.system_bus$publish_BANG_.invokeStatic(system_bus.clj:36)
	at shadow.cljs.devtools.server.system_bus$publish_BANG_.invoke(system_bus.clj:32)
	at shadow.cljs.devtools.server.supervisor$start_worker$fn__15727$state_machine__6772__auto____15770$fn__15772.invoke(supervisor.clj:57)
	at shadow.cljs.devtools.server.supervisor$start_worker$fn__15727$state_machine__6772__auto____15770.invoke(supervisor.clj:56)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__6790.invoke(ioc_macros.clj:986)
shadow-cljs - config: /Users/rick/repos/my-app/shadow-cljs.edn  cli version: 2.8.26  node: v12.4.0
shadow-cljs - starting via "clojure"

```

Alex Miller said this on Clojurians slack about this feature.  I believe enabling it will help you audit shadow-cljs for these potential issues.

> In general, you should never directly or indirectly use blocking IO operations in go block threads. The go block threads are a fixed pool of (by default 8) threads. If you block enough of these threads, you lock up the pool, potentially in unrecoverable ways.
This release contains a new Java system property (intended primarily for development use) that will throw if core.async blocking operations (anything ending in "!!") are used in a go block. The exception will be thrown in a go block thread which by default will bubble up to the ThreadGroup's uncaught exception handler and get printed to stderr. You can also set Thread.setDefaultUncaughtExceptionHandler() if you want to do something else. Note that this only catches one set of blocking calls, other blocking IO is equally as problematic and will not be caught with this flag.
> Example:

```
$ clj -J-Dclojure.core.async.go-checking=true
user=> (require '[clojure.core.async :as a])
nil
user=> (def c (a/chan 10))
#'user/c
user=> (a/go (a/>!! c 100)) ;; => Raises exception
```

**Comment by thheller** [comment]
Hmm this is unfortunate ... The problem is caused here:

https://github.com/thheller/shadow-cljs/blob/719279d63b4b8eec04c4d76170f3bf8b8ce2260e/src/main/shadow/cljs/devtools/server/supervisor.clj#L59

It is basically calling an API method from another namespace, that this namespace is using core.async is an implementation detail that the consumer is not supposed to know or care about. I'll switch it to using proper non-blocking methods instead.
