### ISSUE TITLE
No implementation of method: :close!... while trying to compile an electron project

### ISSUE THREAD

**Issue by mauricioszabo** [thheller/shadow-cljs#698]
I just upgraded Shadow-CLJS on my repl-tooling project, but simply opening the Electron UI (for tests - just opens a devcards index) I'm getting strange errors:

```
shadow-cljs - config: /home/mauricio/.atom/packages/chlorine/repl-tooling/shadow-cljs.edn
shadow-cljs - server version: 2.8.109 running at http://localhost:9630
shadow-cljs - nREPL server started on port 3322
shadow-cljs - watching build :integration
shadow-cljs - watching build :fixture
[:integration] Configuring build.
[:fixture] Configuring build.
Not compiled yet, waiting...
Exception in thread "async-dispatch-3" java.lang.IllegalArgumentException: No implementation of method: :close! of protocol: #'clojure.core.async.impl.protocols/Channel found for class: clojure.lang.PersistentArrayMap
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at clojure.core.async.impl.protocols$eval246$fn__247$G__235__252.invoke(protocols.clj:21)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:979)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at shadow.undertow$fn$reify__16050$fn__16171.invoke(undertow.clj:322)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[:fixture] Compiling ...
[:integration] Compiling ...
[:fixture] Build completed. (55 files, 0 compiled, 0 warnings, 6,22s)
[:integration] Build completed. (323 files, 0 compiled, 0 warnings, 6,43s)
```

Even when everything compiles, I'm getting JS errors of undefined things, for example:

```
failed to load sci.impl.namespaces.js ReferenceError: $m__1101__auto__ is not defined
```

Or sometimes it complains that `$p is not defined`, or other global vars. 

```
╰─>$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

```shadow-cljs - server version: 2.8.109 running at http://localhost:9630```

**Comment by thheller** [comment]
This is caused by using an incompatible `core.async` version. Should be
```
   [org.clojure/core.async "1.1.587"]
```
you likely have an older one specified in your dependencies.

**Comment by mauricioszabo** [comment]
Yes, that was it! Thanks! My fix was just remove `core.async` and use the version that came with Shadow.

I opened the ticket because I saw other errors being printed, but these are probably on my side. Thanks again!
