### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#79]
Hi Thomas, I have an error and this time I don't know where to start debugging.

Basically this is it:

```
eval error TypeError: Cannot read property 'call' of undefined
    at Object.<anonymous> (<eval>:1:-32)
    at Object.SHADOW_ENV.NODE_EVAL ([stdin]:128:13)
    at Object.shadow$cljs$devtools$client$node$node_eval [as node_eval] (/home/arichiardi/git/logpoc/target/shadow-cljs/node-repl/dev/cljs-runtime/shadow/cljs/devtools/client/node.cljs:29:16)
    at /home/arichiardi/git/logpoc/target/shadow-cljs/node-repl/dev/cljs-runtime/shadow/cljs/devtools/client/node.cljs:52:30
    at Object.shadow$cljs$devtools$client$env$repl_call [as repl_call] (/home/arichiardi/git/logpoc/target/shadow-cljs/node-repl/dev/cljs-runtime/shadow/cljs/devtools/client/env.cljs:42:18)
    at Object.shadow$cljs$devtools$client$node$repl_invoke [as repl_invoke] (/home/arichiardi/git/logpoc/target/shadow-cljs/node-repl/dev/cljs-runtime/shadow/cljs/devtools/client/node.cljs:52:13)
    at Object.shadow$cljs$devtools$client$node$process_message [as process_message] (/home/arichiardi/git/logpoc/target/shadow-cljs/node-repl/dev/cljs-runtime/shadow/cljs/devtools/client/node.cljs:117:6)
    at WebSocket.<anonymous> (/home/arichiardi/git/logpoc/target/shadow-cljs/node-repl/dev/cljs-runtime/shadow/cljs/devtools/client/node.cljs:162:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/home/arichiardi/git/logpoc/node_modules/ws/lib/WebSocket.js:143:47)
    at Receiver.dataMessage (/home/arichiardi/git/logpoc/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/arichiardi/git/logpoc/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/arichiardi/git/logpoc/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/arichiardi/git/logpoc/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/arichiardi/git/logpoc/node_modules/ws/lib/WebSocket.js:139:22)
nil
```

Will try to explore and understand what is going on.

**Comment by arichiardi** [comment]
There are a lot of warnings so I will try to fix those first:

```
WARNING: Use of undeclared Var context/msecs-remaining (<stdin> at 8:40)
WARNING: Use of undeclared Var logpoc.core/ctx (<stdin> at 8:64)
WARNING: Use of undeclared Var logpoc.core/deflambda (<stdin> at 2:2)
WARNING: Use of undeclared Var logpoc.core/bunyan-lambda (<stdin> at 2:12)
WARNING: Use of undeclared Var logpoc.core/event (<stdin> at 2:27)
WARNING: Use of undeclared Var logpoc.core/ctx (<stdin> at 2:33)
WARNING: Use of undeclared Var logpoc.core/ctx (<stdin> at 5:47)
WARNING: Use of undeclared Var logpoc.core/ctx (<stdin> at 6:46)
WARNING: Use of undeclared Var logpoc.core/ctx (<stdin> at 7:51)
WARNING: Use of undeclared Var logpoc.core/ctx (<stdin> at 8:64)
```

**Comment by arichiardi** [comment]
Seems like fixing those problems fixes the problem, however maybe the warnings should be redirected through the socket connection to the tool (or I need another connection?).

In any case I am going to leave this one open.

**Comment by thheller** [comment]
Yes, fixing those warnings should fix the problem. It basically tells you that you are calling `something.call(...)` (emitted by `(something :foo)` in CLJS) where `something` is nil/undefined.

I think I should wrap the `eval` in a try/catch so it doesn't show the rest of the useless stacktrace. Everything past `Object.SHADOW_ENV.NODE_EVAL` is useless.
