### ISSUE TITLE
Connection issue with react-native project

### ISSUE THREAD

**Issue by bpringe** [thheller/shadow-cljs#943]
I noticed that with version 2.15.10, when I run the watch process and then start the metro bundler to run the app on an android emulator, I get this warning and error in the terminal where metro is running.

```
The shadow-cljs Websocket was disconnected.
at node_modules/react-native/Libraries/WebSocket/WebSocket.js:260:8 in _eventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit

shadow-cljs - remote-error, Event {
  "isTrusted": false,
  "message": "Failed to connect to localhost/127.0.0.1:9631",
}
at node_modules/react-native/Libraries/WebSocket/WebSocket.js:260:8 in _eventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
```

The error doesn't happen when I use Simulator (iOS).

I tried downgrading to 2.15.5 (after seeing [this comment](https://github.com/thheller/shadow-cljs/issues/940#issuecomment-934556747), and it works fine on an android emulator again.

**Comment by bpringe** [comment]
I verified the above using [rn-rf-shadow](https://github.com/PEZ/rn-rf-shadow) as well.

**Comment by bitkiller42** [comment]
Same problem after update to v2.15.10

```
shadow.user=> (shadow/get-server-addrs)
("192.168.0.54")
```

```
The shadow-cljs Websocket was disconnected.
at node_modules/react-native/Libraries/WebSocket/WebSocket.js:260:8 in _eventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
at [native code]:null in callFunctionReturnFlushedQueue

shadow-cljs - remote-error, Event {
  "isTrusted": false,
  "message": "Failed to connect to localhost/127.0.0.1:9630",
}
at node_modules/react-native/Libraries/WebSocket/WebSocket.js:260:8 in _eventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
at [native code]:null in callFunctionReturnFlushedQueue

shadow-cljs: giving up trying to connect to , ws://localhost:9630/api/remote-relay?server-token=2e1489e1-958c-404d-ac04-1cc8a639ae27
at node_modules/react-native/Libraries/WebSocket/WebSocket.js:265:8 in _eventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
at [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by thheller** [comment]
Same question for you: Do you have :local-ip set anywhere in your shadow-cljs.edn or ~/.shadow-cljs/config.edn?

Why does nobody answer this question?

**Comment by bpringe** [comment]
I don't have `:local-ip` set in either of those locations.

> Can you check shadow-cljs clj-repl and then (shadow/get-server-addrs).

The output is `("192.168.1.6")` and I verified that this is my local IP for my Wi-Fi.

I'm on macOS Big Sur, version 11.6.

**Comment by bpringe** [comment]
@thheller Did you mean to close this? Do you know what might be causing this issue?

**Comment by bpringe** [comment]
Thanks for the fix! The connection works as expected now.
