### ISSUE TITLE
 Unicode comm issue with (Browser) REPL on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [thheller/shadow-cljs#946]
There appears to be an issue with shadow's browser repl on MS-Windows when trying to evaluate Unicode strings which can lead to a server exception such as:

```
Exception in thread "XNIO-1 I/O-7" clojure.lang.ExceptionInfo: failed to transit-read {:in "[\"^ \",\"~:op\",\"~:cljs-compile\",\"~:to\",2,\"~:input\",[\"^ \",\"~:code\",\"\\\"Ï?\\\"\",\"~:ns\",\"~$cljs.user\",\"~:repl\",true],\"~:include-init\",true,\"~:call-id\",0]"}
        at shadow.cljs.devtools.server.common$fn__14932$fn__14933.invoke(common.clj:50)
        at clojure.core$map$fn__5880$fn__5881.invoke(core.clj:2746)
        at clojure.core.async.impl.channels$chan$fn__710.invoke(channels.clj:300)
        at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:83)
        at clojure.core.async$put_BANG_.invokeStatic(async.clj:199)
        at clojure.core.async$put_BANG_.invoke(async.clj:187)
        ...
```

To reproduce with a minimal setup on MS-Windows, just bring up a browser REPL and try to evaluate `"ρ"`:

1. Open a Command Prompt and do `npx create-cljs-project issue-browser-repl-eval-unicode`.
2. `cd issue-browser-repl-eval-unicode`.
3. do `npx shadow-cljs server watch` and take of the the nrepl port.
4. Use your IDE to connect to the nrepl and then start the browser repl: 
    `(do (require '[shadow.cljs.devtools.api :as shadow]) (shadow/browser-repl))`.
5. Open your web browser at the url given by the browser-repl.
6. At the REPL in your IDE, try to evaluate the Unicode string `"ρ"` (Greek letter rho).
7. You should see the exception printed out by the server at the Command Prompt.

The issue is related to the encoding used when marshalling REPL input to and from the web client. 

Patch to follow.

**Comment by thheller** [comment]
Oops, thought I had pushed this update a while ago. It is now part of 2.15.13 though.
